version: "2"

# Options for analysis running.
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: true
  # List of build tags, all linters use it.
  # Default: [].
  modules-download-mode: readonly
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false
  # Define the Go version limit.
  # Mainly related to generics support in go1.18.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.17
  go: "1.24"

# output configuration options
output:
  # Add a prefix to the output file references.
  # Default is no prefix.
  path-prefix: ""
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  #
  # Multiple can be specified by separating them by comma, output can be provided
  # for each of them by separating format name and path by colon symbol.
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  # Example: "checkstyle:report.json,colored-line-number"
  #
  # Default: colored-line-number
  formats:
    text:
      # Print lines of code with issue.
      # Default: true
      print-issued-lines: true
      # Print linter name in the end of issue text.
      # Default: true
      print-linter-name: true
      path: stdout
    tab:
      print-linter-name: true
      path: stdout
  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.

linters:
  default: all
  disable:
    # TODO: Fix imports from Main
    - depguard
    - wsl
    # Allow lines longer than 120 characters
    - lll
    - err113
    - mnd
    # TODO: Fix duplicate code in functions
    - dupl
    # TODO: Allow cyclomatic complexity > 10
    - cyclop
    # Allow long functions
    - funlen
