// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A NetBird Agent Network account-level budget rule: a limit-only rule bound to groups and/or users that applies across all policies as a min-wins ceiling. Empty targets means it applies to every caller.
type AgentNetworkBudgetRule struct {
	pulumi.CustomResourceState

	// Timestamp when the budget rule was created.
	CreatedAt pulumi.StringPtrOutput `pulumi:"createdAt"`
	// Whether the rule is enforced.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Token and budget caps attached directly to the rule.
	Limits AgentNetworkLimitsOutput `pulumi:"limits"`
	// Display name for the budget rule.
	Name pulumi.StringOutput `pulumi:"name"`
	// NetBird group IDs the rule binds.
	TargetGroups pulumi.StringArrayOutput `pulumi:"targetGroups"`
	// NetBird user IDs the rule binds directly.
	TargetUsers pulumi.StringArrayOutput `pulumi:"targetUsers"`
	// Timestamp when the budget rule was last updated.
	UpdatedAt pulumi.StringPtrOutput `pulumi:"updatedAt"`
}

// NewAgentNetworkBudgetRule registers a new resource with the given unique name, arguments, and options.
func NewAgentNetworkBudgetRule(ctx *pulumi.Context,
	name string, args *AgentNetworkBudgetRuleArgs, opts ...pulumi.ResourceOption) (*AgentNetworkBudgetRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Limits == nil {
		return nil, errors.New("invalid value for required argument 'Limits'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AgentNetworkBudgetRule
	err := ctx.RegisterResource("netbird:resource:AgentNetworkBudgetRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAgentNetworkBudgetRule gets an existing AgentNetworkBudgetRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAgentNetworkBudgetRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AgentNetworkBudgetRuleState, opts ...pulumi.ResourceOption) (*AgentNetworkBudgetRule, error) {
	var resource AgentNetworkBudgetRule
	err := ctx.ReadResource("netbird:resource:AgentNetworkBudgetRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AgentNetworkBudgetRule resources.
type agentNetworkBudgetRuleState struct {
}

type AgentNetworkBudgetRuleState struct {
}

func (AgentNetworkBudgetRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*agentNetworkBudgetRuleState)(nil)).Elem()
}

type agentNetworkBudgetRuleArgs struct {
	// Whether the rule is enforced.
	Enabled *bool `pulumi:"enabled"`
	// Token and budget caps attached directly to the rule.
	Limits AgentNetworkLimits `pulumi:"limits"`
	// Display name for the budget rule.
	Name string `pulumi:"name"`
	// NetBird group IDs the rule binds. Empty plus empty targetUsers means account-wide.
	TargetGroups []string `pulumi:"targetGroups"`
	// NetBird user IDs the rule binds directly.
	TargetUsers []string `pulumi:"targetUsers"`
}

// The set of arguments for constructing a AgentNetworkBudgetRule resource.
type AgentNetworkBudgetRuleArgs struct {
	// Whether the rule is enforced.
	Enabled pulumi.BoolPtrInput
	// Token and budget caps attached directly to the rule.
	Limits AgentNetworkLimitsInput
	// Display name for the budget rule.
	Name pulumi.StringInput
	// NetBird group IDs the rule binds. Empty plus empty targetUsers means account-wide.
	TargetGroups pulumi.StringArrayInput
	// NetBird user IDs the rule binds directly.
	TargetUsers pulumi.StringArrayInput
}

func (AgentNetworkBudgetRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*agentNetworkBudgetRuleArgs)(nil)).Elem()
}

type AgentNetworkBudgetRuleInput interface {
	pulumi.Input

	ToAgentNetworkBudgetRuleOutput() AgentNetworkBudgetRuleOutput
	ToAgentNetworkBudgetRuleOutputWithContext(ctx context.Context) AgentNetworkBudgetRuleOutput
}

func (*AgentNetworkBudgetRule) ElementType() reflect.Type {
	return reflect.TypeOf((**AgentNetworkBudgetRule)(nil)).Elem()
}

func (i *AgentNetworkBudgetRule) ToAgentNetworkBudgetRuleOutput() AgentNetworkBudgetRuleOutput {
	return i.ToAgentNetworkBudgetRuleOutputWithContext(context.Background())
}

func (i *AgentNetworkBudgetRule) ToAgentNetworkBudgetRuleOutputWithContext(ctx context.Context) AgentNetworkBudgetRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkBudgetRuleOutput)
}

// AgentNetworkBudgetRuleArrayInput is an input type that accepts AgentNetworkBudgetRuleArray and AgentNetworkBudgetRuleArrayOutput values.
// You can construct a concrete instance of `AgentNetworkBudgetRuleArrayInput` via:
//
//	AgentNetworkBudgetRuleArray{ AgentNetworkBudgetRuleArgs{...} }
type AgentNetworkBudgetRuleArrayInput interface {
	pulumi.Input

	ToAgentNetworkBudgetRuleArrayOutput() AgentNetworkBudgetRuleArrayOutput
	ToAgentNetworkBudgetRuleArrayOutputWithContext(context.Context) AgentNetworkBudgetRuleArrayOutput
}

type AgentNetworkBudgetRuleArray []AgentNetworkBudgetRuleInput

func (AgentNetworkBudgetRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AgentNetworkBudgetRule)(nil)).Elem()
}

func (i AgentNetworkBudgetRuleArray) ToAgentNetworkBudgetRuleArrayOutput() AgentNetworkBudgetRuleArrayOutput {
	return i.ToAgentNetworkBudgetRuleArrayOutputWithContext(context.Background())
}

func (i AgentNetworkBudgetRuleArray) ToAgentNetworkBudgetRuleArrayOutputWithContext(ctx context.Context) AgentNetworkBudgetRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkBudgetRuleArrayOutput)
}

// AgentNetworkBudgetRuleMapInput is an input type that accepts AgentNetworkBudgetRuleMap and AgentNetworkBudgetRuleMapOutput values.
// You can construct a concrete instance of `AgentNetworkBudgetRuleMapInput` via:
//
//	AgentNetworkBudgetRuleMap{ "key": AgentNetworkBudgetRuleArgs{...} }
type AgentNetworkBudgetRuleMapInput interface {
	pulumi.Input

	ToAgentNetworkBudgetRuleMapOutput() AgentNetworkBudgetRuleMapOutput
	ToAgentNetworkBudgetRuleMapOutputWithContext(context.Context) AgentNetworkBudgetRuleMapOutput
}

type AgentNetworkBudgetRuleMap map[string]AgentNetworkBudgetRuleInput

func (AgentNetworkBudgetRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AgentNetworkBudgetRule)(nil)).Elem()
}

func (i AgentNetworkBudgetRuleMap) ToAgentNetworkBudgetRuleMapOutput() AgentNetworkBudgetRuleMapOutput {
	return i.ToAgentNetworkBudgetRuleMapOutputWithContext(context.Background())
}

func (i AgentNetworkBudgetRuleMap) ToAgentNetworkBudgetRuleMapOutputWithContext(ctx context.Context) AgentNetworkBudgetRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkBudgetRuleMapOutput)
}

type AgentNetworkBudgetRuleOutput struct{ *pulumi.OutputState }

func (AgentNetworkBudgetRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AgentNetworkBudgetRule)(nil)).Elem()
}

func (o AgentNetworkBudgetRuleOutput) ToAgentNetworkBudgetRuleOutput() AgentNetworkBudgetRuleOutput {
	return o
}

func (o AgentNetworkBudgetRuleOutput) ToAgentNetworkBudgetRuleOutputWithContext(ctx context.Context) AgentNetworkBudgetRuleOutput {
	return o
}

// Timestamp when the budget rule was created.
func (o AgentNetworkBudgetRuleOutput) CreatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkBudgetRule) pulumi.StringPtrOutput { return v.CreatedAt }).(pulumi.StringPtrOutput)
}

// Whether the rule is enforced.
func (o AgentNetworkBudgetRuleOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AgentNetworkBudgetRule) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Token and budget caps attached directly to the rule.
func (o AgentNetworkBudgetRuleOutput) Limits() AgentNetworkLimitsOutput {
	return o.ApplyT(func(v *AgentNetworkBudgetRule) AgentNetworkLimitsOutput { return v.Limits }).(AgentNetworkLimitsOutput)
}

// Display name for the budget rule.
func (o AgentNetworkBudgetRuleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AgentNetworkBudgetRule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// NetBird group IDs the rule binds.
func (o AgentNetworkBudgetRuleOutput) TargetGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AgentNetworkBudgetRule) pulumi.StringArrayOutput { return v.TargetGroups }).(pulumi.StringArrayOutput)
}

// NetBird user IDs the rule binds directly.
func (o AgentNetworkBudgetRuleOutput) TargetUsers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AgentNetworkBudgetRule) pulumi.StringArrayOutput { return v.TargetUsers }).(pulumi.StringArrayOutput)
}

// Timestamp when the budget rule was last updated.
func (o AgentNetworkBudgetRuleOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkBudgetRule) pulumi.StringPtrOutput { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

type AgentNetworkBudgetRuleArrayOutput struct{ *pulumi.OutputState }

func (AgentNetworkBudgetRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AgentNetworkBudgetRule)(nil)).Elem()
}

func (o AgentNetworkBudgetRuleArrayOutput) ToAgentNetworkBudgetRuleArrayOutput() AgentNetworkBudgetRuleArrayOutput {
	return o
}

func (o AgentNetworkBudgetRuleArrayOutput) ToAgentNetworkBudgetRuleArrayOutputWithContext(ctx context.Context) AgentNetworkBudgetRuleArrayOutput {
	return o
}

func (o AgentNetworkBudgetRuleArrayOutput) Index(i pulumi.IntInput) AgentNetworkBudgetRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AgentNetworkBudgetRule {
		return vs[0].([]*AgentNetworkBudgetRule)[vs[1].(int)]
	}).(AgentNetworkBudgetRuleOutput)
}

type AgentNetworkBudgetRuleMapOutput struct{ *pulumi.OutputState }

func (AgentNetworkBudgetRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AgentNetworkBudgetRule)(nil)).Elem()
}

func (o AgentNetworkBudgetRuleMapOutput) ToAgentNetworkBudgetRuleMapOutput() AgentNetworkBudgetRuleMapOutput {
	return o
}

func (o AgentNetworkBudgetRuleMapOutput) ToAgentNetworkBudgetRuleMapOutputWithContext(ctx context.Context) AgentNetworkBudgetRuleMapOutput {
	return o
}

func (o AgentNetworkBudgetRuleMapOutput) MapIndex(k pulumi.StringInput) AgentNetworkBudgetRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AgentNetworkBudgetRule {
		return vs[0].(map[string]*AgentNetworkBudgetRule)[vs[1].(string)]
	}).(AgentNetworkBudgetRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkBudgetRuleInput)(nil)).Elem(), &AgentNetworkBudgetRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkBudgetRuleArrayInput)(nil)).Elem(), AgentNetworkBudgetRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkBudgetRuleMapInput)(nil)).Elem(), AgentNetworkBudgetRuleMap{})
	pulumi.RegisterOutputType(AgentNetworkBudgetRuleOutput{})
	pulumi.RegisterOutputType(AgentNetworkBudgetRuleArrayOutput{})
	pulumi.RegisterOutputType(AgentNetworkBudgetRuleMapOutput{})
}
