// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Per-account NetBird Agent Network gateway settings. This is a singleton resource — only one instance exists per account. Creating it bootstraps the account's gateway endpoint from exactly one of proxyAddress (the server allocates a label beneath that cluster) or endpoint (the hostname is claimed verbatim as a dedicated endpoint). The assigned endpoint is immutable; changing either field replaces the resource, which releases the endpoint and allocates a new one.
type AgentNetworkSettings struct {
	pulumi.CustomResourceState

	// Days to retain full access-log rows.
	AccessLogRetentionDays pulumi.IntPtrOutput `pulumi:"accessLogRetentionDays"`
	// Timestamp when the settings row was created. Absent until bootstrapped.
	CreatedAt pulumi.StringPtrOutput `pulumi:"createdAt"`
	// Whether the account's gateway is served by a proxy dedicated to it (endpoint equals proxyAddress).
	Dedicated pulumi.BoolOutput `pulumi:"dedicated"`
	// Whether per-request access-log entries are collected.
	EnableLogCollection pulumi.BoolOutput `pulumi:"enableLogCollection"`
	// Master switch for request/response prompt capture.
	EnablePromptCollection pulumi.BoolOutput `pulumi:"enablePromptCollection"`
	// Bare hostname agents call for this account. Empty until bootstrapped.
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
	// Declared cluster address of the proxy serving this account's gateway. Equal to endpoint when a dedicated proxy serves the account; otherwise the endpoint's immediate parent.
	ProxyAddress pulumi.StringPtrOutput `pulumi:"proxyAddress"`
	// Whether captured prompts have PII redacted.
	RedactPii pulumi.BoolOutput `pulumi:"redactPii"`
	// Timestamp when the settings row was last updated. Absent until bootstrapped.
	UpdatedAt pulumi.StringPtrOutput `pulumi:"updatedAt"`
}

// NewAgentNetworkSettings registers a new resource with the given unique name, arguments, and options.
func NewAgentNetworkSettings(ctx *pulumi.Context,
	name string, args *AgentNetworkSettingsArgs, opts ...pulumi.ResourceOption) (*AgentNetworkSettings, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnableLogCollection == nil {
		return nil, errors.New("invalid value for required argument 'EnableLogCollection'")
	}
	if args.EnablePromptCollection == nil {
		return nil, errors.New("invalid value for required argument 'EnablePromptCollection'")
	}
	if args.RedactPii == nil {
		return nil, errors.New("invalid value for required argument 'RedactPii'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AgentNetworkSettings
	err := ctx.RegisterResource("netbird:resource:AgentNetworkSettings", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAgentNetworkSettings gets an existing AgentNetworkSettings resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAgentNetworkSettings(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AgentNetworkSettingsState, opts ...pulumi.ResourceOption) (*AgentNetworkSettings, error) {
	var resource AgentNetworkSettings
	err := ctx.ReadResource("netbird:resource:AgentNetworkSettings", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AgentNetworkSettings resources.
type agentNetworkSettingsState struct {
}

type AgentNetworkSettingsState struct {
}

func (AgentNetworkSettingsState) ElementType() reflect.Type {
	return reflect.TypeOf((*agentNetworkSettingsState)(nil)).Elem()
}

type agentNetworkSettingsArgs struct {
	// Days to retain full access-log rows; older rows are swept. 0 or less means keep indefinitely. Defaults to 30 when omitted.
	AccessLogRetentionDays *int `pulumi:"accessLogRetentionDays"`
	// Whether per-request access-log entries are collected for this account's agent-network traffic.
	EnableLogCollection bool `pulumi:"enableLogCollection"`
	// Master switch for request/response prompt capture. Capture runs only when this is on AND a policy guardrail also enables it.
	EnablePromptCollection bool `pulumi:"enablePromptCollection"`
	// Hostname to claim as the account's self-addressed (dedicated) endpoint, served only by a proxy declaring exactly that address. Mutually exclusive with proxyAddress; exactly one of the two is required. Immutable — changing it replaces the resource.
	Endpoint *string `pulumi:"endpoint"`
	// Cluster address to allocate a labeled endpoint beneath: the server assigns a label and the endpoint becomes `<label>.<proxyAddress>`. Mutually exclusive with endpoint; exactly one of the two is required. Immutable — changing it replaces the resource.
	ProxyAddress *string `pulumi:"proxyAddress"`
	// Whether captured prompts have PII redacted.
	RedactPii bool `pulumi:"redactPii"`
}

// The set of arguments for constructing a AgentNetworkSettings resource.
type AgentNetworkSettingsArgs struct {
	// Days to retain full access-log rows; older rows are swept. 0 or less means keep indefinitely. Defaults to 30 when omitted.
	AccessLogRetentionDays pulumi.IntPtrInput
	// Whether per-request access-log entries are collected for this account's agent-network traffic.
	EnableLogCollection pulumi.BoolInput
	// Master switch for request/response prompt capture. Capture runs only when this is on AND a policy guardrail also enables it.
	EnablePromptCollection pulumi.BoolInput
	// Hostname to claim as the account's self-addressed (dedicated) endpoint, served only by a proxy declaring exactly that address. Mutually exclusive with proxyAddress; exactly one of the two is required. Immutable — changing it replaces the resource.
	Endpoint pulumi.StringPtrInput
	// Cluster address to allocate a labeled endpoint beneath: the server assigns a label and the endpoint becomes `<label>.<proxyAddress>`. Mutually exclusive with endpoint; exactly one of the two is required. Immutable — changing it replaces the resource.
	ProxyAddress pulumi.StringPtrInput
	// Whether captured prompts have PII redacted.
	RedactPii pulumi.BoolInput
}

func (AgentNetworkSettingsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*agentNetworkSettingsArgs)(nil)).Elem()
}

type AgentNetworkSettingsInput interface {
	pulumi.Input

	ToAgentNetworkSettingsOutput() AgentNetworkSettingsOutput
	ToAgentNetworkSettingsOutputWithContext(ctx context.Context) AgentNetworkSettingsOutput
}

func (*AgentNetworkSettings) ElementType() reflect.Type {
	return reflect.TypeOf((**AgentNetworkSettings)(nil)).Elem()
}

func (i *AgentNetworkSettings) ToAgentNetworkSettingsOutput() AgentNetworkSettingsOutput {
	return i.ToAgentNetworkSettingsOutputWithContext(context.Background())
}

func (i *AgentNetworkSettings) ToAgentNetworkSettingsOutputWithContext(ctx context.Context) AgentNetworkSettingsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkSettingsOutput)
}

// AgentNetworkSettingsArrayInput is an input type that accepts AgentNetworkSettingsArray and AgentNetworkSettingsArrayOutput values.
// You can construct a concrete instance of `AgentNetworkSettingsArrayInput` via:
//
//	AgentNetworkSettingsArray{ AgentNetworkSettingsArgs{...} }
type AgentNetworkSettingsArrayInput interface {
	pulumi.Input

	ToAgentNetworkSettingsArrayOutput() AgentNetworkSettingsArrayOutput
	ToAgentNetworkSettingsArrayOutputWithContext(context.Context) AgentNetworkSettingsArrayOutput
}

type AgentNetworkSettingsArray []AgentNetworkSettingsInput

func (AgentNetworkSettingsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AgentNetworkSettings)(nil)).Elem()
}

func (i AgentNetworkSettingsArray) ToAgentNetworkSettingsArrayOutput() AgentNetworkSettingsArrayOutput {
	return i.ToAgentNetworkSettingsArrayOutputWithContext(context.Background())
}

func (i AgentNetworkSettingsArray) ToAgentNetworkSettingsArrayOutputWithContext(ctx context.Context) AgentNetworkSettingsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkSettingsArrayOutput)
}

// AgentNetworkSettingsMapInput is an input type that accepts AgentNetworkSettingsMap and AgentNetworkSettingsMapOutput values.
// You can construct a concrete instance of `AgentNetworkSettingsMapInput` via:
//
//	AgentNetworkSettingsMap{ "key": AgentNetworkSettingsArgs{...} }
type AgentNetworkSettingsMapInput interface {
	pulumi.Input

	ToAgentNetworkSettingsMapOutput() AgentNetworkSettingsMapOutput
	ToAgentNetworkSettingsMapOutputWithContext(context.Context) AgentNetworkSettingsMapOutput
}

type AgentNetworkSettingsMap map[string]AgentNetworkSettingsInput

func (AgentNetworkSettingsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AgentNetworkSettings)(nil)).Elem()
}

func (i AgentNetworkSettingsMap) ToAgentNetworkSettingsMapOutput() AgentNetworkSettingsMapOutput {
	return i.ToAgentNetworkSettingsMapOutputWithContext(context.Background())
}

func (i AgentNetworkSettingsMap) ToAgentNetworkSettingsMapOutputWithContext(ctx context.Context) AgentNetworkSettingsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkSettingsMapOutput)
}

type AgentNetworkSettingsOutput struct{ *pulumi.OutputState }

func (AgentNetworkSettingsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AgentNetworkSettings)(nil)).Elem()
}

func (o AgentNetworkSettingsOutput) ToAgentNetworkSettingsOutput() AgentNetworkSettingsOutput {
	return o
}

func (o AgentNetworkSettingsOutput) ToAgentNetworkSettingsOutputWithContext(ctx context.Context) AgentNetworkSettingsOutput {
	return o
}

// Days to retain full access-log rows.
func (o AgentNetworkSettingsOutput) AccessLogRetentionDays() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.IntPtrOutput { return v.AccessLogRetentionDays }).(pulumi.IntPtrOutput)
}

// Timestamp when the settings row was created. Absent until bootstrapped.
func (o AgentNetworkSettingsOutput) CreatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.StringPtrOutput { return v.CreatedAt }).(pulumi.StringPtrOutput)
}

// Whether the account's gateway is served by a proxy dedicated to it (endpoint equals proxyAddress).
func (o AgentNetworkSettingsOutput) Dedicated() pulumi.BoolOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.BoolOutput { return v.Dedicated }).(pulumi.BoolOutput)
}

// Whether per-request access-log entries are collected.
func (o AgentNetworkSettingsOutput) EnableLogCollection() pulumi.BoolOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.BoolOutput { return v.EnableLogCollection }).(pulumi.BoolOutput)
}

// Master switch for request/response prompt capture.
func (o AgentNetworkSettingsOutput) EnablePromptCollection() pulumi.BoolOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.BoolOutput { return v.EnablePromptCollection }).(pulumi.BoolOutput)
}

// Bare hostname agents call for this account. Empty until bootstrapped.
func (o AgentNetworkSettingsOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

// Declared cluster address of the proxy serving this account's gateway. Equal to endpoint when a dedicated proxy serves the account; otherwise the endpoint's immediate parent.
func (o AgentNetworkSettingsOutput) ProxyAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.StringPtrOutput { return v.ProxyAddress }).(pulumi.StringPtrOutput)
}

// Whether captured prompts have PII redacted.
func (o AgentNetworkSettingsOutput) RedactPii() pulumi.BoolOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.BoolOutput { return v.RedactPii }).(pulumi.BoolOutput)
}

// Timestamp when the settings row was last updated. Absent until bootstrapped.
func (o AgentNetworkSettingsOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkSettings) pulumi.StringPtrOutput { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

type AgentNetworkSettingsArrayOutput struct{ *pulumi.OutputState }

func (AgentNetworkSettingsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AgentNetworkSettings)(nil)).Elem()
}

func (o AgentNetworkSettingsArrayOutput) ToAgentNetworkSettingsArrayOutput() AgentNetworkSettingsArrayOutput {
	return o
}

func (o AgentNetworkSettingsArrayOutput) ToAgentNetworkSettingsArrayOutputWithContext(ctx context.Context) AgentNetworkSettingsArrayOutput {
	return o
}

func (o AgentNetworkSettingsArrayOutput) Index(i pulumi.IntInput) AgentNetworkSettingsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AgentNetworkSettings {
		return vs[0].([]*AgentNetworkSettings)[vs[1].(int)]
	}).(AgentNetworkSettingsOutput)
}

type AgentNetworkSettingsMapOutput struct{ *pulumi.OutputState }

func (AgentNetworkSettingsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AgentNetworkSettings)(nil)).Elem()
}

func (o AgentNetworkSettingsMapOutput) ToAgentNetworkSettingsMapOutput() AgentNetworkSettingsMapOutput {
	return o
}

func (o AgentNetworkSettingsMapOutput) ToAgentNetworkSettingsMapOutputWithContext(ctx context.Context) AgentNetworkSettingsMapOutput {
	return o
}

func (o AgentNetworkSettingsMapOutput) MapIndex(k pulumi.StringInput) AgentNetworkSettingsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AgentNetworkSettings {
		return vs[0].(map[string]*AgentNetworkSettings)[vs[1].(string)]
	}).(AgentNetworkSettingsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkSettingsInput)(nil)).Elem(), &AgentNetworkSettings{})
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkSettingsArrayInput)(nil)).Elem(), AgentNetworkSettingsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkSettingsMapInput)(nil)).Elem(), AgentNetworkSettingsMap{})
	pulumi.RegisterOutputType(AgentNetworkSettingsOutput{})
	pulumi.RegisterOutputType(AgentNetworkSettingsArrayOutput{})
	pulumi.RegisterOutputType(AgentNetworkSettingsMapOutput{})
}
