// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A NetBird Agent Network provider: an upstream AI/LLM API or gateway (OpenAI, Anthropic, Bedrock, LiteLLM, a custom OpenAI-compatible endpoint, ...) that policies can route traffic to.
type AgentNetworkProvider struct {
	pulumi.CustomResourceState

	// Upstream provider API key. Not returned by the API; preserved from configuration.
	ApiKey pulumi.StringOutput `pulumi:"apiKey"`
	// Timestamp when the provider was created.
	CreatedAt pulumi.StringPtrOutput `pulumi:"createdAt"`
	// Whether the provider is enabled.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Operator-typed values for catalog-declared extra headers.
	ExtraValues pulumi.StringMapOutput `pulumi:"extraValues"`
	// Wire header name for the caller's NetBird groups.
	IdentityHeaderGroups pulumi.StringPtrOutput `pulumi:"identityHeaderGroups"`
	// Wire header name for the caller's display identity.
	IdentityHeaderUserId pulumi.StringPtrOutput `pulumi:"identityHeaderUserId"`
	// Whether identity metadata injection is disabled for this provider.
	MetadataDisabled pulumi.BoolPtrOutput `pulumi:"metadataDisabled"`
	// Models exposed through this endpoint, with operator per-1k price overrides.
	Models AgentNetworkProviderModelPricingArrayOutput `pulumi:"models"`
	// Display name shown in the dashboard.
	Name pulumi.StringOutput `pulumi:"name"`
	// Catalog identifier for the upstream AI provider.
	ProviderId pulumi.StringOutput `pulumi:"providerId"`
	// Whether upstream TLS certificate verification is skipped.
	SkipTlsVerification pulumi.BoolPtrOutput `pulumi:"skipTlsVerification"`
	// Timestamp when the provider was last updated.
	UpdatedAt pulumi.StringPtrOutput `pulumi:"updatedAt"`
	// Full upstream URL (with scheme) that NetBird forwards traffic to.
	UpstreamUrl pulumi.StringOutput `pulumi:"upstreamUrl"`
}

// NewAgentNetworkProvider registers a new resource with the given unique name, arguments, and options.
func NewAgentNetworkProvider(ctx *pulumi.Context,
	name string, args *AgentNetworkProviderArgs, opts ...pulumi.ResourceOption) (*AgentNetworkProvider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApiKey == nil {
		return nil, errors.New("invalid value for required argument 'ApiKey'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.ProviderId == nil {
		return nil, errors.New("invalid value for required argument 'ProviderId'")
	}
	if args.UpstreamUrl == nil {
		return nil, errors.New("invalid value for required argument 'UpstreamUrl'")
	}
	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AgentNetworkProvider
	err := ctx.RegisterResource("netbird:resource:AgentNetworkProvider", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAgentNetworkProvider gets an existing AgentNetworkProvider resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAgentNetworkProvider(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AgentNetworkProviderState, opts ...pulumi.ResourceOption) (*AgentNetworkProvider, error) {
	var resource AgentNetworkProvider
	err := ctx.ReadResource("netbird:resource:AgentNetworkProvider", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AgentNetworkProvider resources.
type agentNetworkProviderState struct {
}

type AgentNetworkProviderState struct {
}

func (AgentNetworkProviderState) ElementType() reflect.Type {
	return reflect.TypeOf((*agentNetworkProviderState)(nil)).Elem()
}

type agentNetworkProviderArgs struct {
	// Upstream provider API key. Sealed at rest on the management server and never returned in responses.
	ApiKey string `pulumi:"apiKey"`
	// Deprecated and ignored. NetBird removed bootstrap_cluster from the provider API; bootstrap the account's gateway endpoint with netbird:resource:AgentNetworkSettings (proxyAddress or endpoint) instead.
	//
	// Deprecated: bootstrapCluster is ignored. Bootstrap the account gateway with AgentNetworkSettings (proxyAddress or endpoint).
	BootstrapCluster *string `pulumi:"bootstrapCluster"`
	// Whether the provider is enabled.
	Enabled *bool `pulumi:"enabled"`
	// Operator-typed values for catalog-declared extra headers (see getAgentNetworkCatalogProviders).
	ExtraValues map[string]string `pulumi:"extraValues"`
	// Wire header name the proxy stamps with the caller's NetBird groups (comma-separated), when the catalog entry supports customizable identity headers.
	IdentityHeaderGroups *string `pulumi:"identityHeaderGroups"`
	// Wire header name the proxy stamps with the caller's display identity, when the catalog entry supports customizable identity headers.
	IdentityHeaderUserId *string `pulumi:"identityHeaderUserId"`
	// Disable identity metadata injection (caller's user + authorizing group) for this provider.
	MetadataDisabled *bool `pulumi:"metadataDisabled"`
	// Models exposed through this endpoint, with operator per-1k price overrides. Empty means all catalog models are allowed at catalog prices.
	Models []AgentNetworkProviderModelPricing `pulumi:"models"`
	// Display name shown in the dashboard.
	Name string `pulumi:"name"`
	// Catalog identifier for the upstream AI provider (e.g. openai_api, anthropic_api, azure_openai_api, bedrock_api, vertex_ai_api, mistral_api, custom). See getAgentNetworkCatalogProviders. Changing this forces a replacement.
	ProviderId string `pulumi:"providerId"`
	// Skip upstream TLS certificate verification. For self-hosted / internal gateways with a private or self-signed certificate.
	SkipTlsVerification *bool `pulumi:"skipTlsVerification"`
	// Full upstream URL (with scheme) that NetBird forwards traffic to.
	UpstreamUrl string `pulumi:"upstreamUrl"`
}

// The set of arguments for constructing a AgentNetworkProvider resource.
type AgentNetworkProviderArgs struct {
	// Upstream provider API key. Sealed at rest on the management server and never returned in responses.
	ApiKey pulumi.StringInput
	// Deprecated and ignored. NetBird removed bootstrap_cluster from the provider API; bootstrap the account's gateway endpoint with netbird:resource:AgentNetworkSettings (proxyAddress or endpoint) instead.
	//
	// Deprecated: bootstrapCluster is ignored. Bootstrap the account gateway with AgentNetworkSettings (proxyAddress or endpoint).
	BootstrapCluster pulumi.StringPtrInput
	// Whether the provider is enabled.
	Enabled pulumi.BoolPtrInput
	// Operator-typed values for catalog-declared extra headers (see getAgentNetworkCatalogProviders).
	ExtraValues pulumi.StringMapInput
	// Wire header name the proxy stamps with the caller's NetBird groups (comma-separated), when the catalog entry supports customizable identity headers.
	IdentityHeaderGroups pulumi.StringPtrInput
	// Wire header name the proxy stamps with the caller's display identity, when the catalog entry supports customizable identity headers.
	IdentityHeaderUserId pulumi.StringPtrInput
	// Disable identity metadata injection (caller's user + authorizing group) for this provider.
	MetadataDisabled pulumi.BoolPtrInput
	// Models exposed through this endpoint, with operator per-1k price overrides. Empty means all catalog models are allowed at catalog prices.
	Models AgentNetworkProviderModelPricingArrayInput
	// Display name shown in the dashboard.
	Name pulumi.StringInput
	// Catalog identifier for the upstream AI provider (e.g. openai_api, anthropic_api, azure_openai_api, bedrock_api, vertex_ai_api, mistral_api, custom). See getAgentNetworkCatalogProviders. Changing this forces a replacement.
	ProviderId pulumi.StringInput
	// Skip upstream TLS certificate verification. For self-hosted / internal gateways with a private or self-signed certificate.
	SkipTlsVerification pulumi.BoolPtrInput
	// Full upstream URL (with scheme) that NetBird forwards traffic to.
	UpstreamUrl pulumi.StringInput
}

func (AgentNetworkProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*agentNetworkProviderArgs)(nil)).Elem()
}

type AgentNetworkProviderInput interface {
	pulumi.Input

	ToAgentNetworkProviderOutput() AgentNetworkProviderOutput
	ToAgentNetworkProviderOutputWithContext(ctx context.Context) AgentNetworkProviderOutput
}

func (*AgentNetworkProvider) ElementType() reflect.Type {
	return reflect.TypeOf((**AgentNetworkProvider)(nil)).Elem()
}

func (i *AgentNetworkProvider) ToAgentNetworkProviderOutput() AgentNetworkProviderOutput {
	return i.ToAgentNetworkProviderOutputWithContext(context.Background())
}

func (i *AgentNetworkProvider) ToAgentNetworkProviderOutputWithContext(ctx context.Context) AgentNetworkProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkProviderOutput)
}

// AgentNetworkProviderArrayInput is an input type that accepts AgentNetworkProviderArray and AgentNetworkProviderArrayOutput values.
// You can construct a concrete instance of `AgentNetworkProviderArrayInput` via:
//
//	AgentNetworkProviderArray{ AgentNetworkProviderArgs{...} }
type AgentNetworkProviderArrayInput interface {
	pulumi.Input

	ToAgentNetworkProviderArrayOutput() AgentNetworkProviderArrayOutput
	ToAgentNetworkProviderArrayOutputWithContext(context.Context) AgentNetworkProviderArrayOutput
}

type AgentNetworkProviderArray []AgentNetworkProviderInput

func (AgentNetworkProviderArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AgentNetworkProvider)(nil)).Elem()
}

func (i AgentNetworkProviderArray) ToAgentNetworkProviderArrayOutput() AgentNetworkProviderArrayOutput {
	return i.ToAgentNetworkProviderArrayOutputWithContext(context.Background())
}

func (i AgentNetworkProviderArray) ToAgentNetworkProviderArrayOutputWithContext(ctx context.Context) AgentNetworkProviderArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkProviderArrayOutput)
}

// AgentNetworkProviderMapInput is an input type that accepts AgentNetworkProviderMap and AgentNetworkProviderMapOutput values.
// You can construct a concrete instance of `AgentNetworkProviderMapInput` via:
//
//	AgentNetworkProviderMap{ "key": AgentNetworkProviderArgs{...} }
type AgentNetworkProviderMapInput interface {
	pulumi.Input

	ToAgentNetworkProviderMapOutput() AgentNetworkProviderMapOutput
	ToAgentNetworkProviderMapOutputWithContext(context.Context) AgentNetworkProviderMapOutput
}

type AgentNetworkProviderMap map[string]AgentNetworkProviderInput

func (AgentNetworkProviderMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AgentNetworkProvider)(nil)).Elem()
}

func (i AgentNetworkProviderMap) ToAgentNetworkProviderMapOutput() AgentNetworkProviderMapOutput {
	return i.ToAgentNetworkProviderMapOutputWithContext(context.Background())
}

func (i AgentNetworkProviderMap) ToAgentNetworkProviderMapOutputWithContext(ctx context.Context) AgentNetworkProviderMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AgentNetworkProviderMapOutput)
}

type AgentNetworkProviderOutput struct{ *pulumi.OutputState }

func (AgentNetworkProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AgentNetworkProvider)(nil)).Elem()
}

func (o AgentNetworkProviderOutput) ToAgentNetworkProviderOutput() AgentNetworkProviderOutput {
	return o
}

func (o AgentNetworkProviderOutput) ToAgentNetworkProviderOutputWithContext(ctx context.Context) AgentNetworkProviderOutput {
	return o
}

// Upstream provider API key. Not returned by the API; preserved from configuration.
func (o AgentNetworkProviderOutput) ApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringOutput { return v.ApiKey }).(pulumi.StringOutput)
}

// Timestamp when the provider was created.
func (o AgentNetworkProviderOutput) CreatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringPtrOutput { return v.CreatedAt }).(pulumi.StringPtrOutput)
}

// Whether the provider is enabled.
func (o AgentNetworkProviderOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Operator-typed values for catalog-declared extra headers.
func (o AgentNetworkProviderOutput) ExtraValues() pulumi.StringMapOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringMapOutput { return v.ExtraValues }).(pulumi.StringMapOutput)
}

// Wire header name for the caller's NetBird groups.
func (o AgentNetworkProviderOutput) IdentityHeaderGroups() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringPtrOutput { return v.IdentityHeaderGroups }).(pulumi.StringPtrOutput)
}

// Wire header name for the caller's display identity.
func (o AgentNetworkProviderOutput) IdentityHeaderUserId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringPtrOutput { return v.IdentityHeaderUserId }).(pulumi.StringPtrOutput)
}

// Whether identity metadata injection is disabled for this provider.
func (o AgentNetworkProviderOutput) MetadataDisabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.BoolPtrOutput { return v.MetadataDisabled }).(pulumi.BoolPtrOutput)
}

// Models exposed through this endpoint, with operator per-1k price overrides.
func (o AgentNetworkProviderOutput) Models() AgentNetworkProviderModelPricingArrayOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) AgentNetworkProviderModelPricingArrayOutput { return v.Models }).(AgentNetworkProviderModelPricingArrayOutput)
}

// Display name shown in the dashboard.
func (o AgentNetworkProviderOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Catalog identifier for the upstream AI provider.
func (o AgentNetworkProviderOutput) ProviderId() pulumi.StringOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringOutput { return v.ProviderId }).(pulumi.StringOutput)
}

// Whether upstream TLS certificate verification is skipped.
func (o AgentNetworkProviderOutput) SkipTlsVerification() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.BoolPtrOutput { return v.SkipTlsVerification }).(pulumi.BoolPtrOutput)
}

// Timestamp when the provider was last updated.
func (o AgentNetworkProviderOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringPtrOutput { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

// Full upstream URL (with scheme) that NetBird forwards traffic to.
func (o AgentNetworkProviderOutput) UpstreamUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *AgentNetworkProvider) pulumi.StringOutput { return v.UpstreamUrl }).(pulumi.StringOutput)
}

type AgentNetworkProviderArrayOutput struct{ *pulumi.OutputState }

func (AgentNetworkProviderArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AgentNetworkProvider)(nil)).Elem()
}

func (o AgentNetworkProviderArrayOutput) ToAgentNetworkProviderArrayOutput() AgentNetworkProviderArrayOutput {
	return o
}

func (o AgentNetworkProviderArrayOutput) ToAgentNetworkProviderArrayOutputWithContext(ctx context.Context) AgentNetworkProviderArrayOutput {
	return o
}

func (o AgentNetworkProviderArrayOutput) Index(i pulumi.IntInput) AgentNetworkProviderOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AgentNetworkProvider {
		return vs[0].([]*AgentNetworkProvider)[vs[1].(int)]
	}).(AgentNetworkProviderOutput)
}

type AgentNetworkProviderMapOutput struct{ *pulumi.OutputState }

func (AgentNetworkProviderMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AgentNetworkProvider)(nil)).Elem()
}

func (o AgentNetworkProviderMapOutput) ToAgentNetworkProviderMapOutput() AgentNetworkProviderMapOutput {
	return o
}

func (o AgentNetworkProviderMapOutput) ToAgentNetworkProviderMapOutputWithContext(ctx context.Context) AgentNetworkProviderMapOutput {
	return o
}

func (o AgentNetworkProviderMapOutput) MapIndex(k pulumi.StringInput) AgentNetworkProviderOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AgentNetworkProvider {
		return vs[0].(map[string]*AgentNetworkProvider)[vs[1].(string)]
	}).(AgentNetworkProviderOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkProviderInput)(nil)).Elem(), &AgentNetworkProvider{})
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkProviderArrayInput)(nil)).Elem(), AgentNetworkProviderArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AgentNetworkProviderMapInput)(nil)).Elem(), AgentNetworkProviderMap{})
	pulumi.RegisterOutputType(AgentNetworkProviderOutput{})
	pulumi.RegisterOutputType(AgentNetworkProviderArrayOutput{})
	pulumi.RegisterOutputType(AgentNetworkProviderMapOutput{})
}
