// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// NetBird global DNS settings. This is a singleton resource — only one instance exists per account.
type DNSSettings struct {
	pulumi.CustomResourceState

	// Group IDs whose DNS management is disabled.
	DisabledManagementGroups pulumi.StringArrayOutput `pulumi:"disabledManagementGroups"`
}

// NewDNSSettings registers a new resource with the given unique name, arguments, and options.
func NewDNSSettings(ctx *pulumi.Context,
	name string, args *DNSSettingsArgs, opts ...pulumi.ResourceOption) (*DNSSettings, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DisabledManagementGroups == nil {
		return nil, errors.New("invalid value for required argument 'DisabledManagementGroups'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DNSSettings
	err := ctx.RegisterResource("netbird:resource:DNSSettings", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDNSSettings gets an existing DNSSettings resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDNSSettings(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DNSSettingsState, opts ...pulumi.ResourceOption) (*DNSSettings, error) {
	var resource DNSSettings
	err := ctx.ReadResource("netbird:resource:DNSSettings", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DNSSettings resources.
type dnssettingsState struct {
}

type DNSSettingsState struct {
}

func (DNSSettingsState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnssettingsState)(nil)).Elem()
}

type dnssettingsArgs struct {
	// Group IDs whose DNS management is disabled.
	DisabledManagementGroups []string `pulumi:"disabledManagementGroups"`
}

// The set of arguments for constructing a DNSSettings resource.
type DNSSettingsArgs struct {
	// Group IDs whose DNS management is disabled.
	DisabledManagementGroups pulumi.StringArrayInput
}

func (DNSSettingsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnssettingsArgs)(nil)).Elem()
}

type DNSSettingsInput interface {
	pulumi.Input

	ToDNSSettingsOutput() DNSSettingsOutput
	ToDNSSettingsOutputWithContext(ctx context.Context) DNSSettingsOutput
}

func (*DNSSettings) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSSettings)(nil)).Elem()
}

func (i *DNSSettings) ToDNSSettingsOutput() DNSSettingsOutput {
	return i.ToDNSSettingsOutputWithContext(context.Background())
}

func (i *DNSSettings) ToDNSSettingsOutputWithContext(ctx context.Context) DNSSettingsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSSettingsOutput)
}

// DNSSettingsArrayInput is an input type that accepts DNSSettingsArray and DNSSettingsArrayOutput values.
// You can construct a concrete instance of `DNSSettingsArrayInput` via:
//
//	DNSSettingsArray{ DNSSettingsArgs{...} }
type DNSSettingsArrayInput interface {
	pulumi.Input

	ToDNSSettingsArrayOutput() DNSSettingsArrayOutput
	ToDNSSettingsArrayOutputWithContext(context.Context) DNSSettingsArrayOutput
}

type DNSSettingsArray []DNSSettingsInput

func (DNSSettingsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSSettings)(nil)).Elem()
}

func (i DNSSettingsArray) ToDNSSettingsArrayOutput() DNSSettingsArrayOutput {
	return i.ToDNSSettingsArrayOutputWithContext(context.Background())
}

func (i DNSSettingsArray) ToDNSSettingsArrayOutputWithContext(ctx context.Context) DNSSettingsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSSettingsArrayOutput)
}

// DNSSettingsMapInput is an input type that accepts DNSSettingsMap and DNSSettingsMapOutput values.
// You can construct a concrete instance of `DNSSettingsMapInput` via:
//
//	DNSSettingsMap{ "key": DNSSettingsArgs{...} }
type DNSSettingsMapInput interface {
	pulumi.Input

	ToDNSSettingsMapOutput() DNSSettingsMapOutput
	ToDNSSettingsMapOutputWithContext(context.Context) DNSSettingsMapOutput
}

type DNSSettingsMap map[string]DNSSettingsInput

func (DNSSettingsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSSettings)(nil)).Elem()
}

func (i DNSSettingsMap) ToDNSSettingsMapOutput() DNSSettingsMapOutput {
	return i.ToDNSSettingsMapOutputWithContext(context.Background())
}

func (i DNSSettingsMap) ToDNSSettingsMapOutputWithContext(ctx context.Context) DNSSettingsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSSettingsMapOutput)
}

type DNSSettingsOutput struct{ *pulumi.OutputState }

func (DNSSettingsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSSettings)(nil)).Elem()
}

func (o DNSSettingsOutput) ToDNSSettingsOutput() DNSSettingsOutput {
	return o
}

func (o DNSSettingsOutput) ToDNSSettingsOutputWithContext(ctx context.Context) DNSSettingsOutput {
	return o
}

// Group IDs whose DNS management is disabled.
func (o DNSSettingsOutput) DisabledManagementGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DNSSettings) pulumi.StringArrayOutput { return v.DisabledManagementGroups }).(pulumi.StringArrayOutput)
}

type DNSSettingsArrayOutput struct{ *pulumi.OutputState }

func (DNSSettingsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSSettings)(nil)).Elem()
}

func (o DNSSettingsArrayOutput) ToDNSSettingsArrayOutput() DNSSettingsArrayOutput {
	return o
}

func (o DNSSettingsArrayOutput) ToDNSSettingsArrayOutputWithContext(ctx context.Context) DNSSettingsArrayOutput {
	return o
}

func (o DNSSettingsArrayOutput) Index(i pulumi.IntInput) DNSSettingsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DNSSettings {
		return vs[0].([]*DNSSettings)[vs[1].(int)]
	}).(DNSSettingsOutput)
}

type DNSSettingsMapOutput struct{ *pulumi.OutputState }

func (DNSSettingsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSSettings)(nil)).Elem()
}

func (o DNSSettingsMapOutput) ToDNSSettingsMapOutput() DNSSettingsMapOutput {
	return o
}

func (o DNSSettingsMapOutput) ToDNSSettingsMapOutputWithContext(ctx context.Context) DNSSettingsMapOutput {
	return o
}

func (o DNSSettingsMapOutput) MapIndex(k pulumi.StringInput) DNSSettingsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DNSSettings {
		return vs[0].(map[string]*DNSSettings)[vs[1].(string)]
	}).(DNSSettingsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DNSSettingsInput)(nil)).Elem(), &DNSSettings{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSSettingsArrayInput)(nil)).Elem(), DNSSettingsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSSettingsMapInput)(nil)).Elem(), DNSSettingsMap{})
	pulumi.RegisterOutputType(DNSSettingsOutput{})
	pulumi.RegisterOutputType(DNSSettingsArrayOutput{})
	pulumi.RegisterOutputType(DNSSettingsMapOutput{})
}
