// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A NetBird DNS zone.
type DNSZone struct {
	pulumi.CustomResourceState

	// Group IDs that define groups of peers that will resolve this zone.
	DistributionGroups pulumi.StringArrayOutput `pulumi:"distributionGroups"`
	// Zone domain (FQDN).
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Enable this zone as a search domain.
	EnableSearchDomain pulumi.BoolOutput `pulumi:"enableSearchDomain"`
	// Zone status.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Zone name identifier.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewDNSZone registers a new resource with the given unique name, arguments, and options.
func NewDNSZone(ctx *pulumi.Context,
	name string, args *DNSZoneArgs, opts ...pulumi.ResourceOption) (*DNSZone, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DistributionGroups == nil {
		return nil, errors.New("invalid value for required argument 'DistributionGroups'")
	}
	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.EnableSearchDomain == nil {
		return nil, errors.New("invalid value for required argument 'EnableSearchDomain'")
	}
	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DNSZone
	err := ctx.RegisterResource("netbird:resource:DNSZone", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDNSZone gets an existing DNSZone resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDNSZone(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DNSZoneState, opts ...pulumi.ResourceOption) (*DNSZone, error) {
	var resource DNSZone
	err := ctx.ReadResource("netbird:resource:DNSZone", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DNSZone resources.
type dnszoneState struct {
}

type DNSZoneState struct {
}

func (DNSZoneState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnszoneState)(nil)).Elem()
}

type dnszoneArgs struct {
	// Group IDs that define groups of peers that will resolve this zone.
	DistributionGroups []string `pulumi:"distributionGroups"`
	// Zone domain (FQDN).
	Domain string `pulumi:"domain"`
	// Enable this zone as a search domain.
	EnableSearchDomain bool `pulumi:"enableSearchDomain"`
	// Zone status.
	Enabled bool `pulumi:"enabled"`
	// Zone name identifier.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a DNSZone resource.
type DNSZoneArgs struct {
	// Group IDs that define groups of peers that will resolve this zone.
	DistributionGroups pulumi.StringArrayInput
	// Zone domain (FQDN).
	Domain pulumi.StringInput
	// Enable this zone as a search domain.
	EnableSearchDomain pulumi.BoolInput
	// Zone status.
	Enabled pulumi.BoolInput
	// Zone name identifier.
	Name pulumi.StringInput
}

func (DNSZoneArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnszoneArgs)(nil)).Elem()
}

type DNSZoneInput interface {
	pulumi.Input

	ToDNSZoneOutput() DNSZoneOutput
	ToDNSZoneOutputWithContext(ctx context.Context) DNSZoneOutput
}

func (*DNSZone) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSZone)(nil)).Elem()
}

func (i *DNSZone) ToDNSZoneOutput() DNSZoneOutput {
	return i.ToDNSZoneOutputWithContext(context.Background())
}

func (i *DNSZone) ToDNSZoneOutputWithContext(ctx context.Context) DNSZoneOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSZoneOutput)
}

// DNSZoneArrayInput is an input type that accepts DNSZoneArray and DNSZoneArrayOutput values.
// You can construct a concrete instance of `DNSZoneArrayInput` via:
//
//	DNSZoneArray{ DNSZoneArgs{...} }
type DNSZoneArrayInput interface {
	pulumi.Input

	ToDNSZoneArrayOutput() DNSZoneArrayOutput
	ToDNSZoneArrayOutputWithContext(context.Context) DNSZoneArrayOutput
}

type DNSZoneArray []DNSZoneInput

func (DNSZoneArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSZone)(nil)).Elem()
}

func (i DNSZoneArray) ToDNSZoneArrayOutput() DNSZoneArrayOutput {
	return i.ToDNSZoneArrayOutputWithContext(context.Background())
}

func (i DNSZoneArray) ToDNSZoneArrayOutputWithContext(ctx context.Context) DNSZoneArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSZoneArrayOutput)
}

// DNSZoneMapInput is an input type that accepts DNSZoneMap and DNSZoneMapOutput values.
// You can construct a concrete instance of `DNSZoneMapInput` via:
//
//	DNSZoneMap{ "key": DNSZoneArgs{...} }
type DNSZoneMapInput interface {
	pulumi.Input

	ToDNSZoneMapOutput() DNSZoneMapOutput
	ToDNSZoneMapOutputWithContext(context.Context) DNSZoneMapOutput
}

type DNSZoneMap map[string]DNSZoneInput

func (DNSZoneMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSZone)(nil)).Elem()
}

func (i DNSZoneMap) ToDNSZoneMapOutput() DNSZoneMapOutput {
	return i.ToDNSZoneMapOutputWithContext(context.Background())
}

func (i DNSZoneMap) ToDNSZoneMapOutputWithContext(ctx context.Context) DNSZoneMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSZoneMapOutput)
}

type DNSZoneOutput struct{ *pulumi.OutputState }

func (DNSZoneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSZone)(nil)).Elem()
}

func (o DNSZoneOutput) ToDNSZoneOutput() DNSZoneOutput {
	return o
}

func (o DNSZoneOutput) ToDNSZoneOutputWithContext(ctx context.Context) DNSZoneOutput {
	return o
}

// Group IDs that define groups of peers that will resolve this zone.
func (o DNSZoneOutput) DistributionGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DNSZone) pulumi.StringArrayOutput { return v.DistributionGroups }).(pulumi.StringArrayOutput)
}

// Zone domain (FQDN).
func (o DNSZoneOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *DNSZone) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Enable this zone as a search domain.
func (o DNSZoneOutput) EnableSearchDomain() pulumi.BoolOutput {
	return o.ApplyT(func(v *DNSZone) pulumi.BoolOutput { return v.EnableSearchDomain }).(pulumi.BoolOutput)
}

// Zone status.
func (o DNSZoneOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DNSZone) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Zone name identifier.
func (o DNSZoneOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DNSZone) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type DNSZoneArrayOutput struct{ *pulumi.OutputState }

func (DNSZoneArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSZone)(nil)).Elem()
}

func (o DNSZoneArrayOutput) ToDNSZoneArrayOutput() DNSZoneArrayOutput {
	return o
}

func (o DNSZoneArrayOutput) ToDNSZoneArrayOutputWithContext(ctx context.Context) DNSZoneArrayOutput {
	return o
}

func (o DNSZoneArrayOutput) Index(i pulumi.IntInput) DNSZoneOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DNSZone {
		return vs[0].([]*DNSZone)[vs[1].(int)]
	}).(DNSZoneOutput)
}

type DNSZoneMapOutput struct{ *pulumi.OutputState }

func (DNSZoneMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSZone)(nil)).Elem()
}

func (o DNSZoneMapOutput) ToDNSZoneMapOutput() DNSZoneMapOutput {
	return o
}

func (o DNSZoneMapOutput) ToDNSZoneMapOutputWithContext(ctx context.Context) DNSZoneMapOutput {
	return o
}

func (o DNSZoneMapOutput) MapIndex(k pulumi.StringInput) DNSZoneOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DNSZone {
		return vs[0].(map[string]*DNSZone)[vs[1].(string)]
	}).(DNSZoneOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DNSZoneInput)(nil)).Elem(), &DNSZone{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSZoneArrayInput)(nil)).Elem(), DNSZoneArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSZoneMapInput)(nil)).Elem(), DNSZoneMap{})
	pulumi.RegisterOutputType(DNSZoneOutput{})
	pulumi.RegisterOutputType(DNSZoneArrayOutput{})
	pulumi.RegisterOutputType(DNSZoneMapOutput{})
}
