// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A NetBird Google Workspace identity-provider sync integration.
type GoogleIDP struct {
	pulumi.CustomResourceState

	// DEX connector ID for embedded IdP setups.
	ConnectorId pulumi.StringPtrOutput `pulumi:"connectorId"`
	// Customer ID from Google Workspace account settings.
	CustomerId pulumi.StringOutput `pulumi:"customerId"`
	// Whether the integration is enabled.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// start_with patterns for groups to sync.
	GroupPrefixes pulumi.StringArrayOutput `pulumi:"groupPrefixes"`
	// Timestamp of the last synchronization.
	LastSyncedAt pulumi.StringPtrOutput `pulumi:"lastSyncedAt"`
	// Base64-encoded Google service account key. Not returned by the API; preserved from configuration.
	ServiceAccountKey pulumi.StringOutput `pulumi:"serviceAccountKey"`
	// Sync interval in seconds.
	SyncInterval pulumi.IntPtrOutput `pulumi:"syncInterval"`
	// start_with patterns for groups whose users to sync.
	UserGroupPrefixes pulumi.StringArrayOutput `pulumi:"userGroupPrefixes"`
}

// NewGoogleIDP registers a new resource with the given unique name, arguments, and options.
func NewGoogleIDP(ctx *pulumi.Context,
	name string, args *GoogleIDPArgs, opts ...pulumi.ResourceOption) (*GoogleIDP, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CustomerId == nil {
		return nil, errors.New("invalid value for required argument 'CustomerId'")
	}
	if args.ServiceAccountKey == nil {
		return nil, errors.New("invalid value for required argument 'ServiceAccountKey'")
	}
	if args.ServiceAccountKey != nil {
		args.ServiceAccountKey = pulumi.ToSecret(args.ServiceAccountKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"serviceAccountKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GoogleIDP
	err := ctx.RegisterResource("netbird:resource:GoogleIDP", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGoogleIDP gets an existing GoogleIDP resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGoogleIDP(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GoogleIDPState, opts ...pulumi.ResourceOption) (*GoogleIDP, error) {
	var resource GoogleIDP
	err := ctx.ReadResource("netbird:resource:GoogleIDP", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GoogleIDP resources.
type googleIDPState struct {
}

type GoogleIDPState struct {
}

func (GoogleIDPState) ElementType() reflect.Type {
	return reflect.TypeOf((*googleIDPState)(nil)).Elem()
}

type googleIDPArgs struct {
	// DEX connector ID for embedded IdP setups.
	ConnectorId *string `pulumi:"connectorId"`
	// Customer ID from Google Workspace account settings.
	CustomerId string `pulumi:"customerId"`
	// Whether the integration is enabled.
	Enabled *bool `pulumi:"enabled"`
	// start_with patterns for groups to sync.
	GroupPrefixes []string `pulumi:"groupPrefixes"`
	// Base64-encoded Google service account key.
	ServiceAccountKey string `pulumi:"serviceAccountKey"`
	// Sync interval in seconds (minimum 300).
	SyncInterval *int `pulumi:"syncInterval"`
	// start_with patterns for groups whose users to sync.
	UserGroupPrefixes []string `pulumi:"userGroupPrefixes"`
}

// The set of arguments for constructing a GoogleIDP resource.
type GoogleIDPArgs struct {
	// DEX connector ID for embedded IdP setups.
	ConnectorId pulumi.StringPtrInput
	// Customer ID from Google Workspace account settings.
	CustomerId pulumi.StringInput
	// Whether the integration is enabled.
	Enabled pulumi.BoolPtrInput
	// start_with patterns for groups to sync.
	GroupPrefixes pulumi.StringArrayInput
	// Base64-encoded Google service account key.
	ServiceAccountKey pulumi.StringInput
	// Sync interval in seconds (minimum 300).
	SyncInterval pulumi.IntPtrInput
	// start_with patterns for groups whose users to sync.
	UserGroupPrefixes pulumi.StringArrayInput
}

func (GoogleIDPArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*googleIDPArgs)(nil)).Elem()
}

type GoogleIDPInput interface {
	pulumi.Input

	ToGoogleIDPOutput() GoogleIDPOutput
	ToGoogleIDPOutputWithContext(ctx context.Context) GoogleIDPOutput
}

func (*GoogleIDP) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleIDP)(nil)).Elem()
}

func (i *GoogleIDP) ToGoogleIDPOutput() GoogleIDPOutput {
	return i.ToGoogleIDPOutputWithContext(context.Background())
}

func (i *GoogleIDP) ToGoogleIDPOutputWithContext(ctx context.Context) GoogleIDPOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleIDPOutput)
}

// GoogleIDPArrayInput is an input type that accepts GoogleIDPArray and GoogleIDPArrayOutput values.
// You can construct a concrete instance of `GoogleIDPArrayInput` via:
//
//	GoogleIDPArray{ GoogleIDPArgs{...} }
type GoogleIDPArrayInput interface {
	pulumi.Input

	ToGoogleIDPArrayOutput() GoogleIDPArrayOutput
	ToGoogleIDPArrayOutputWithContext(context.Context) GoogleIDPArrayOutput
}

type GoogleIDPArray []GoogleIDPInput

func (GoogleIDPArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GoogleIDP)(nil)).Elem()
}

func (i GoogleIDPArray) ToGoogleIDPArrayOutput() GoogleIDPArrayOutput {
	return i.ToGoogleIDPArrayOutputWithContext(context.Background())
}

func (i GoogleIDPArray) ToGoogleIDPArrayOutputWithContext(ctx context.Context) GoogleIDPArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleIDPArrayOutput)
}

// GoogleIDPMapInput is an input type that accepts GoogleIDPMap and GoogleIDPMapOutput values.
// You can construct a concrete instance of `GoogleIDPMapInput` via:
//
//	GoogleIDPMap{ "key": GoogleIDPArgs{...} }
type GoogleIDPMapInput interface {
	pulumi.Input

	ToGoogleIDPMapOutput() GoogleIDPMapOutput
	ToGoogleIDPMapOutputWithContext(context.Context) GoogleIDPMapOutput
}

type GoogleIDPMap map[string]GoogleIDPInput

func (GoogleIDPMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GoogleIDP)(nil)).Elem()
}

func (i GoogleIDPMap) ToGoogleIDPMapOutput() GoogleIDPMapOutput {
	return i.ToGoogleIDPMapOutputWithContext(context.Background())
}

func (i GoogleIDPMap) ToGoogleIDPMapOutputWithContext(ctx context.Context) GoogleIDPMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleIDPMapOutput)
}

type GoogleIDPOutput struct{ *pulumi.OutputState }

func (GoogleIDPOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleIDP)(nil)).Elem()
}

func (o GoogleIDPOutput) ToGoogleIDPOutput() GoogleIDPOutput {
	return o
}

func (o GoogleIDPOutput) ToGoogleIDPOutputWithContext(ctx context.Context) GoogleIDPOutput {
	return o
}

// DEX connector ID for embedded IdP setups.
func (o GoogleIDPOutput) ConnectorId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.StringPtrOutput { return v.ConnectorId }).(pulumi.StringPtrOutput)
}

// Customer ID from Google Workspace account settings.
func (o GoogleIDPOutput) CustomerId() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.StringOutput { return v.CustomerId }).(pulumi.StringOutput)
}

// Whether the integration is enabled.
func (o GoogleIDPOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// start_with patterns for groups to sync.
func (o GoogleIDPOutput) GroupPrefixes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.StringArrayOutput { return v.GroupPrefixes }).(pulumi.StringArrayOutput)
}

// Timestamp of the last synchronization.
func (o GoogleIDPOutput) LastSyncedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.StringPtrOutput { return v.LastSyncedAt }).(pulumi.StringPtrOutput)
}

// Base64-encoded Google service account key. Not returned by the API; preserved from configuration.
func (o GoogleIDPOutput) ServiceAccountKey() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.StringOutput { return v.ServiceAccountKey }).(pulumi.StringOutput)
}

// Sync interval in seconds.
func (o GoogleIDPOutput) SyncInterval() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.IntPtrOutput { return v.SyncInterval }).(pulumi.IntPtrOutput)
}

// start_with patterns for groups whose users to sync.
func (o GoogleIDPOutput) UserGroupPrefixes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GoogleIDP) pulumi.StringArrayOutput { return v.UserGroupPrefixes }).(pulumi.StringArrayOutput)
}

type GoogleIDPArrayOutput struct{ *pulumi.OutputState }

func (GoogleIDPArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GoogleIDP)(nil)).Elem()
}

func (o GoogleIDPArrayOutput) ToGoogleIDPArrayOutput() GoogleIDPArrayOutput {
	return o
}

func (o GoogleIDPArrayOutput) ToGoogleIDPArrayOutputWithContext(ctx context.Context) GoogleIDPArrayOutput {
	return o
}

func (o GoogleIDPArrayOutput) Index(i pulumi.IntInput) GoogleIDPOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GoogleIDP {
		return vs[0].([]*GoogleIDP)[vs[1].(int)]
	}).(GoogleIDPOutput)
}

type GoogleIDPMapOutput struct{ *pulumi.OutputState }

func (GoogleIDPMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GoogleIDP)(nil)).Elem()
}

func (o GoogleIDPMapOutput) ToGoogleIDPMapOutput() GoogleIDPMapOutput {
	return o
}

func (o GoogleIDPMapOutput) ToGoogleIDPMapOutputWithContext(ctx context.Context) GoogleIDPMapOutput {
	return o
}

func (o GoogleIDPMapOutput) MapIndex(k pulumi.StringInput) GoogleIDPOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GoogleIDP {
		return vs[0].(map[string]*GoogleIDP)[vs[1].(string)]
	}).(GoogleIDPOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleIDPInput)(nil)).Elem(), &GoogleIDP{})
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleIDPArrayInput)(nil)).Elem(), GoogleIDPArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleIDPMapInput)(nil)).Elem(), GoogleIDPMap{})
	pulumi.RegisterOutputType(GoogleIDPOutput{})
	pulumi.RegisterOutputType(GoogleIDPArrayOutput{})
	pulumi.RegisterOutputType(GoogleIDPMapOutput{})
}
