// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NameserverNsType string

const (
	// UDP type
	NameserverNsTypeUdp = NameserverNsType("udp")
)

func (NameserverNsType) ElementType() reflect.Type {
	return reflect.TypeOf((*NameserverNsType)(nil)).Elem()
}

func (e NameserverNsType) ToNameserverNsTypeOutput() NameserverNsTypeOutput {
	return pulumi.ToOutput(e).(NameserverNsTypeOutput)
}

func (e NameserverNsType) ToNameserverNsTypeOutputWithContext(ctx context.Context) NameserverNsTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(NameserverNsTypeOutput)
}

func (e NameserverNsType) ToNameserverNsTypePtrOutput() NameserverNsTypePtrOutput {
	return e.ToNameserverNsTypePtrOutputWithContext(context.Background())
}

func (e NameserverNsType) ToNameserverNsTypePtrOutputWithContext(ctx context.Context) NameserverNsTypePtrOutput {
	return NameserverNsType(e).ToNameserverNsTypeOutputWithContext(ctx).ToNameserverNsTypePtrOutputWithContext(ctx)
}

func (e NameserverNsType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e NameserverNsType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e NameserverNsType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e NameserverNsType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type NameserverNsTypeOutput struct{ *pulumi.OutputState }

func (NameserverNsTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NameserverNsType)(nil)).Elem()
}

func (o NameserverNsTypeOutput) ToNameserverNsTypeOutput() NameserverNsTypeOutput {
	return o
}

func (o NameserverNsTypeOutput) ToNameserverNsTypeOutputWithContext(ctx context.Context) NameserverNsTypeOutput {
	return o
}

func (o NameserverNsTypeOutput) ToNameserverNsTypePtrOutput() NameserverNsTypePtrOutput {
	return o.ToNameserverNsTypePtrOutputWithContext(context.Background())
}

func (o NameserverNsTypeOutput) ToNameserverNsTypePtrOutputWithContext(ctx context.Context) NameserverNsTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v NameserverNsType) *NameserverNsType {
		return &v
	}).(NameserverNsTypePtrOutput)
}

func (o NameserverNsTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o NameserverNsTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e NameserverNsType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o NameserverNsTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o NameserverNsTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e NameserverNsType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type NameserverNsTypePtrOutput struct{ *pulumi.OutputState }

func (NameserverNsTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NameserverNsType)(nil)).Elem()
}

func (o NameserverNsTypePtrOutput) ToNameserverNsTypePtrOutput() NameserverNsTypePtrOutput {
	return o
}

func (o NameserverNsTypePtrOutput) ToNameserverNsTypePtrOutputWithContext(ctx context.Context) NameserverNsTypePtrOutput {
	return o
}

func (o NameserverNsTypePtrOutput) Elem() NameserverNsTypeOutput {
	return o.ApplyT(func(v *NameserverNsType) NameserverNsType {
		if v != nil {
			return *v
		}
		var ret NameserverNsType
		return ret
	}).(NameserverNsTypeOutput)
}

func (o NameserverNsTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o NameserverNsTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *NameserverNsType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// NameserverNsTypeInput is an input type that accepts values of the NameserverNsType enum
// A concrete instance of `NameserverNsTypeInput` can be one of the following:
//
//	NameserverNsTypeUdp
type NameserverNsTypeInput interface {
	pulumi.Input

	ToNameserverNsTypeOutput() NameserverNsTypeOutput
	ToNameserverNsTypeOutputWithContext(context.Context) NameserverNsTypeOutput
}

var nameserverNsTypePtrType = reflect.TypeOf((**NameserverNsType)(nil)).Elem()

type NameserverNsTypePtrInput interface {
	pulumi.Input

	ToNameserverNsTypePtrOutput() NameserverNsTypePtrOutput
	ToNameserverNsTypePtrOutputWithContext(context.Context) NameserverNsTypePtrOutput
}

type nameserverNsTypePtr string

func NameserverNsTypePtr(v string) NameserverNsTypePtrInput {
	return (*nameserverNsTypePtr)(&v)
}

func (*nameserverNsTypePtr) ElementType() reflect.Type {
	return nameserverNsTypePtrType
}

func (in *nameserverNsTypePtr) ToNameserverNsTypePtrOutput() NameserverNsTypePtrOutput {
	return pulumi.ToOutput(in).(NameserverNsTypePtrOutput)
}

func (in *nameserverNsTypePtr) ToNameserverNsTypePtrOutputWithContext(ctx context.Context) NameserverNsTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(NameserverNsTypePtrOutput)
}

type Protocol string

const (
	// All protocols
	ProtocolAll = Protocol("all")
	// ICMP protocol
	ProtocolIcmp = Protocol("icmp")
	// TCP protocol
	ProtocolTcp = Protocol("tcp")
	// UDP protocol
	ProtocolUdp = Protocol("udp")
)

func (Protocol) ElementType() reflect.Type {
	return reflect.TypeOf((*Protocol)(nil)).Elem()
}

func (e Protocol) ToProtocolOutput() ProtocolOutput {
	return pulumi.ToOutput(e).(ProtocolOutput)
}

func (e Protocol) ToProtocolOutputWithContext(ctx context.Context) ProtocolOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ProtocolOutput)
}

func (e Protocol) ToProtocolPtrOutput() ProtocolPtrOutput {
	return e.ToProtocolPtrOutputWithContext(context.Background())
}

func (e Protocol) ToProtocolPtrOutputWithContext(ctx context.Context) ProtocolPtrOutput {
	return Protocol(e).ToProtocolOutputWithContext(ctx).ToProtocolPtrOutputWithContext(ctx)
}

func (e Protocol) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e Protocol) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e Protocol) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e Protocol) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ProtocolOutput struct{ *pulumi.OutputState }

func (ProtocolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Protocol)(nil)).Elem()
}

func (o ProtocolOutput) ToProtocolOutput() ProtocolOutput {
	return o
}

func (o ProtocolOutput) ToProtocolOutputWithContext(ctx context.Context) ProtocolOutput {
	return o
}

func (o ProtocolOutput) ToProtocolPtrOutput() ProtocolPtrOutput {
	return o.ToProtocolPtrOutputWithContext(context.Background())
}

func (o ProtocolOutput) ToProtocolPtrOutputWithContext(ctx context.Context) ProtocolPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Protocol) *Protocol {
		return &v
	}).(ProtocolPtrOutput)
}

func (o ProtocolOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ProtocolOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Protocol) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ProtocolOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ProtocolOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Protocol) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ProtocolPtrOutput struct{ *pulumi.OutputState }

func (ProtocolPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Protocol)(nil)).Elem()
}

func (o ProtocolPtrOutput) ToProtocolPtrOutput() ProtocolPtrOutput {
	return o
}

func (o ProtocolPtrOutput) ToProtocolPtrOutputWithContext(ctx context.Context) ProtocolPtrOutput {
	return o
}

func (o ProtocolPtrOutput) Elem() ProtocolOutput {
	return o.ApplyT(func(v *Protocol) Protocol {
		if v != nil {
			return *v
		}
		var ret Protocol
		return ret
	}).(ProtocolOutput)
}

func (o ProtocolPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ProtocolPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Protocol) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ProtocolInput is an input type that accepts values of the Protocol enum
// A concrete instance of `ProtocolInput` can be one of the following:
//
//	ProtocolAll
//	ProtocolIcmp
//	ProtocolTcp
//	ProtocolUdp
type ProtocolInput interface {
	pulumi.Input

	ToProtocolOutput() ProtocolOutput
	ToProtocolOutputWithContext(context.Context) ProtocolOutput
}

var protocolPtrType = reflect.TypeOf((**Protocol)(nil)).Elem()

type ProtocolPtrInput interface {
	pulumi.Input

	ToProtocolPtrOutput() ProtocolPtrOutput
	ToProtocolPtrOutputWithContext(context.Context) ProtocolPtrOutput
}

type protocolPtr string

func ProtocolPtr(v string) ProtocolPtrInput {
	return (*protocolPtr)(&v)
}

func (*protocolPtr) ElementType() reflect.Type {
	return protocolPtrType
}

func (in *protocolPtr) ToProtocolPtrOutput() ProtocolPtrOutput {
	return pulumi.ToOutput(in).(ProtocolPtrOutput)
}

func (in *protocolPtr) ToProtocolPtrOutputWithContext(ctx context.Context) ProtocolPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ProtocolPtrOutput)
}

type ResourceType string

const (
	// A domain resource (e.g., example.com).
	ResourceTypeDomain = ResourceType("domain")
	// A host resource (e.g., peer or device).
	ResourceTypeHost = ResourceType("host")
	// A subnet resource (e.g., 192.168.0.0/24).
	ResourceTypeSubnet = ResourceType("subnet")
)

func (ResourceType) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceType)(nil)).Elem()
}

func (e ResourceType) ToResourceTypeOutput() ResourceTypeOutput {
	return pulumi.ToOutput(e).(ResourceTypeOutput)
}

func (e ResourceType) ToResourceTypeOutputWithContext(ctx context.Context) ResourceTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ResourceTypeOutput)
}

func (e ResourceType) ToResourceTypePtrOutput() ResourceTypePtrOutput {
	return e.ToResourceTypePtrOutputWithContext(context.Background())
}

func (e ResourceType) ToResourceTypePtrOutputWithContext(ctx context.Context) ResourceTypePtrOutput {
	return ResourceType(e).ToResourceTypeOutputWithContext(ctx).ToResourceTypePtrOutputWithContext(ctx)
}

func (e ResourceType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ResourceType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ResourceType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ResourceType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ResourceTypeOutput struct{ *pulumi.OutputState }

func (ResourceTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceType)(nil)).Elem()
}

func (o ResourceTypeOutput) ToResourceTypeOutput() ResourceTypeOutput {
	return o
}

func (o ResourceTypeOutput) ToResourceTypeOutputWithContext(ctx context.Context) ResourceTypeOutput {
	return o
}

func (o ResourceTypeOutput) ToResourceTypePtrOutput() ResourceTypePtrOutput {
	return o.ToResourceTypePtrOutputWithContext(context.Background())
}

func (o ResourceTypeOutput) ToResourceTypePtrOutputWithContext(ctx context.Context) ResourceTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ResourceType) *ResourceType {
		return &v
	}).(ResourceTypePtrOutput)
}

func (o ResourceTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ResourceTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ResourceType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ResourceTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ResourceTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ResourceType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ResourceTypePtrOutput struct{ *pulumi.OutputState }

func (ResourceTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceType)(nil)).Elem()
}

func (o ResourceTypePtrOutput) ToResourceTypePtrOutput() ResourceTypePtrOutput {
	return o
}

func (o ResourceTypePtrOutput) ToResourceTypePtrOutputWithContext(ctx context.Context) ResourceTypePtrOutput {
	return o
}

func (o ResourceTypePtrOutput) Elem() ResourceTypeOutput {
	return o.ApplyT(func(v *ResourceType) ResourceType {
		if v != nil {
			return *v
		}
		var ret ResourceType
		return ret
	}).(ResourceTypeOutput)
}

func (o ResourceTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ResourceTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ResourceType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ResourceTypeInput is an input type that accepts values of the ResourceType enum
// A concrete instance of `ResourceTypeInput` can be one of the following:
//
//	ResourceTypeDomain
//	ResourceTypeHost
//	ResourceTypeSubnet
type ResourceTypeInput interface {
	pulumi.Input

	ToResourceTypeOutput() ResourceTypeOutput
	ToResourceTypeOutputWithContext(context.Context) ResourceTypeOutput
}

var resourceTypePtrType = reflect.TypeOf((**ResourceType)(nil)).Elem()

type ResourceTypePtrInput interface {
	pulumi.Input

	ToResourceTypePtrOutput() ResourceTypePtrOutput
	ToResourceTypePtrOutputWithContext(context.Context) ResourceTypePtrOutput
}

type resourceTypePtr string

func ResourceTypePtr(v string) ResourceTypePtrInput {
	return (*resourceTypePtr)(&v)
}

func (*resourceTypePtr) ElementType() reflect.Type {
	return resourceTypePtrType
}

func (in *resourceTypePtr) ToResourceTypePtrOutput() ResourceTypePtrOutput {
	return pulumi.ToOutput(in).(ResourceTypePtrOutput)
}

func (in *resourceTypePtr) ToResourceTypePtrOutputWithContext(ctx context.Context) ResourceTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ResourceTypePtrOutput)
}

type RuleAction string

const (
	// Accept action
	RuleActionAccept = RuleAction("accept")
	// Drop action
	RuleActionDrop = RuleAction("drop")
)

func (RuleAction) ElementType() reflect.Type {
	return reflect.TypeOf((*RuleAction)(nil)).Elem()
}

func (e RuleAction) ToRuleActionOutput() RuleActionOutput {
	return pulumi.ToOutput(e).(RuleActionOutput)
}

func (e RuleAction) ToRuleActionOutputWithContext(ctx context.Context) RuleActionOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RuleActionOutput)
}

func (e RuleAction) ToRuleActionPtrOutput() RuleActionPtrOutput {
	return e.ToRuleActionPtrOutputWithContext(context.Background())
}

func (e RuleAction) ToRuleActionPtrOutputWithContext(ctx context.Context) RuleActionPtrOutput {
	return RuleAction(e).ToRuleActionOutputWithContext(ctx).ToRuleActionPtrOutputWithContext(ctx)
}

func (e RuleAction) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e RuleAction) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e RuleAction) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e RuleAction) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RuleActionOutput struct{ *pulumi.OutputState }

func (RuleActionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RuleAction)(nil)).Elem()
}

func (o RuleActionOutput) ToRuleActionOutput() RuleActionOutput {
	return o
}

func (o RuleActionOutput) ToRuleActionOutputWithContext(ctx context.Context) RuleActionOutput {
	return o
}

func (o RuleActionOutput) ToRuleActionPtrOutput() RuleActionPtrOutput {
	return o.ToRuleActionPtrOutputWithContext(context.Background())
}

func (o RuleActionOutput) ToRuleActionPtrOutputWithContext(ctx context.Context) RuleActionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RuleAction) *RuleAction {
		return &v
	}).(RuleActionPtrOutput)
}

func (o RuleActionOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RuleActionOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RuleAction) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RuleActionOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RuleActionOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RuleAction) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RuleActionPtrOutput struct{ *pulumi.OutputState }

func (RuleActionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RuleAction)(nil)).Elem()
}

func (o RuleActionPtrOutput) ToRuleActionPtrOutput() RuleActionPtrOutput {
	return o
}

func (o RuleActionPtrOutput) ToRuleActionPtrOutputWithContext(ctx context.Context) RuleActionPtrOutput {
	return o
}

func (o RuleActionPtrOutput) Elem() RuleActionOutput {
	return o.ApplyT(func(v *RuleAction) RuleAction {
		if v != nil {
			return *v
		}
		var ret RuleAction
		return ret
	}).(RuleActionOutput)
}

func (o RuleActionPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RuleActionPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *RuleAction) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RuleActionInput is an input type that accepts values of the RuleAction enum
// A concrete instance of `RuleActionInput` can be one of the following:
//
//	RuleActionAccept
//	RuleActionDrop
type RuleActionInput interface {
	pulumi.Input

	ToRuleActionOutput() RuleActionOutput
	ToRuleActionOutputWithContext(context.Context) RuleActionOutput
}

var ruleActionPtrType = reflect.TypeOf((**RuleAction)(nil)).Elem()

type RuleActionPtrInput interface {
	pulumi.Input

	ToRuleActionPtrOutput() RuleActionPtrOutput
	ToRuleActionPtrOutputWithContext(context.Context) RuleActionPtrOutput
}

type ruleActionPtr string

func RuleActionPtr(v string) RuleActionPtrInput {
	return (*ruleActionPtr)(&v)
}

func (*ruleActionPtr) ElementType() reflect.Type {
	return ruleActionPtrType
}

func (in *ruleActionPtr) ToRuleActionPtrOutput() RuleActionPtrOutput {
	return pulumi.ToOutput(in).(RuleActionPtrOutput)
}

func (in *ruleActionPtr) ToRuleActionPtrOutputWithContext(ctx context.Context) RuleActionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RuleActionPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NameserverNsTypeInput)(nil)).Elem(), NameserverNsType("udp"))
	pulumi.RegisterInputType(reflect.TypeOf((*NameserverNsTypePtrInput)(nil)).Elem(), NameserverNsType("udp"))
	pulumi.RegisterInputType(reflect.TypeOf((*ProtocolInput)(nil)).Elem(), Protocol("all"))
	pulumi.RegisterInputType(reflect.TypeOf((*ProtocolPtrInput)(nil)).Elem(), Protocol("all"))
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceTypeInput)(nil)).Elem(), ResourceType("domain"))
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceTypePtrInput)(nil)).Elem(), ResourceType("domain"))
	pulumi.RegisterInputType(reflect.TypeOf((*RuleActionInput)(nil)).Elem(), RuleAction("accept"))
	pulumi.RegisterInputType(reflect.TypeOf((*RuleActionPtrInput)(nil)).Elem(), RuleAction("accept"))
	pulumi.RegisterOutputType(NameserverNsTypeOutput{})
	pulumi.RegisterOutputType(NameserverNsTypePtrOutput{})
	pulumi.RegisterOutputType(ProtocolOutput{})
	pulumi.RegisterOutputType(ProtocolPtrOutput{})
	pulumi.RegisterOutputType(ResourceTypeOutput{})
	pulumi.RegisterOutputType(ResourceTypePtrOutput{})
	pulumi.RegisterOutputType(RuleActionOutput{})
	pulumi.RegisterOutputType(RuleActionPtrOutput{})
}
