// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A NetBird reverse proxy service.
type ReverseProxyService struct {
	pulumi.CustomResourceState

	// Domain for the service.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Whether the service is enabled.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Port the proxy listens on (L4/TLS only).
	ListenPort pulumi.IntPtrOutput `pulumi:"listenPort"`
	// Service mode: "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough.
	Mode ReverseProxyServiceModePtrOutput `pulumi:"mode"`
	// Service name.
	Name pulumi.StringOutput `pulumi:"name"`
	// When true, the original client Host header is passed through to the backend.
	PassHostHeader pulumi.BoolPtrOutput `pulumi:"passHostHeader"`
	// The proxy cluster handling this service (derived from domain).
	ProxyCluster pulumi.StringPtrOutput `pulumi:"proxyCluster"`
	// When true, Location headers in backend responses are rewritten to the public-facing domain.
	RewriteRedirects pulumi.BoolPtrOutput `pulumi:"rewriteRedirects"`
	// Current status of the service.
	Status pulumi.StringPtrOutput `pulumi:"status"`
	// List of target backends for this service.
	Targets ReverseProxyTargetArrayOutput `pulumi:"targets"`
}

// NewReverseProxyService registers a new resource with the given unique name, arguments, and options.
func NewReverseProxyService(ctx *pulumi.Context,
	name string, args *ReverseProxyServiceArgs, opts ...pulumi.ResourceOption) (*ReverseProxyService, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Targets == nil {
		return nil, errors.New("invalid value for required argument 'Targets'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ReverseProxyService
	err := ctx.RegisterResource("netbird:resource:ReverseProxyService", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetReverseProxyService gets an existing ReverseProxyService resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetReverseProxyService(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ReverseProxyServiceState, opts ...pulumi.ResourceOption) (*ReverseProxyService, error) {
	var resource ReverseProxyService
	err := ctx.ReadResource("netbird:resource:ReverseProxyService", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ReverseProxyService resources.
type reverseProxyServiceState struct {
}

type ReverseProxyServiceState struct {
}

func (ReverseProxyServiceState) ElementType() reflect.Type {
	return reflect.TypeOf((*reverseProxyServiceState)(nil)).Elem()
}

type reverseProxyServiceArgs struct {
	// Domain for the service.
	Domain string `pulumi:"domain"`
	// Whether the service is enabled.
	Enabled bool `pulumi:"enabled"`
	// Port the proxy listens on (L4/TLS only). Set to 0 for auto-assignment.
	ListenPort *int `pulumi:"listenPort"`
	// Service mode: "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough.
	Mode *ReverseProxyServiceMode `pulumi:"mode"`
	// Service name.
	Name string `pulumi:"name"`
	// When true, the original client Host header is passed through to the backend.
	PassHostHeader *bool `pulumi:"passHostHeader"`
	// When true, Location headers in backend responses are rewritten to the public-facing domain.
	RewriteRedirects *bool `pulumi:"rewriteRedirects"`
	// List of target backends for this service.
	Targets []ReverseProxyTarget `pulumi:"targets"`
}

// The set of arguments for constructing a ReverseProxyService resource.
type ReverseProxyServiceArgs struct {
	// Domain for the service.
	Domain pulumi.StringInput
	// Whether the service is enabled.
	Enabled pulumi.BoolInput
	// Port the proxy listens on (L4/TLS only). Set to 0 for auto-assignment.
	ListenPort pulumi.IntPtrInput
	// Service mode: "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough.
	Mode ReverseProxyServiceModePtrInput
	// Service name.
	Name pulumi.StringInput
	// When true, the original client Host header is passed through to the backend.
	PassHostHeader pulumi.BoolPtrInput
	// When true, Location headers in backend responses are rewritten to the public-facing domain.
	RewriteRedirects pulumi.BoolPtrInput
	// List of target backends for this service.
	Targets ReverseProxyTargetArrayInput
}

func (ReverseProxyServiceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*reverseProxyServiceArgs)(nil)).Elem()
}

type ReverseProxyServiceInput interface {
	pulumi.Input

	ToReverseProxyServiceOutput() ReverseProxyServiceOutput
	ToReverseProxyServiceOutputWithContext(ctx context.Context) ReverseProxyServiceOutput
}

func (*ReverseProxyService) ElementType() reflect.Type {
	return reflect.TypeOf((**ReverseProxyService)(nil)).Elem()
}

func (i *ReverseProxyService) ToReverseProxyServiceOutput() ReverseProxyServiceOutput {
	return i.ToReverseProxyServiceOutputWithContext(context.Background())
}

func (i *ReverseProxyService) ToReverseProxyServiceOutputWithContext(ctx context.Context) ReverseProxyServiceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReverseProxyServiceOutput)
}

// ReverseProxyServiceArrayInput is an input type that accepts ReverseProxyServiceArray and ReverseProxyServiceArrayOutput values.
// You can construct a concrete instance of `ReverseProxyServiceArrayInput` via:
//
//	ReverseProxyServiceArray{ ReverseProxyServiceArgs{...} }
type ReverseProxyServiceArrayInput interface {
	pulumi.Input

	ToReverseProxyServiceArrayOutput() ReverseProxyServiceArrayOutput
	ToReverseProxyServiceArrayOutputWithContext(context.Context) ReverseProxyServiceArrayOutput
}

type ReverseProxyServiceArray []ReverseProxyServiceInput

func (ReverseProxyServiceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReverseProxyService)(nil)).Elem()
}

func (i ReverseProxyServiceArray) ToReverseProxyServiceArrayOutput() ReverseProxyServiceArrayOutput {
	return i.ToReverseProxyServiceArrayOutputWithContext(context.Background())
}

func (i ReverseProxyServiceArray) ToReverseProxyServiceArrayOutputWithContext(ctx context.Context) ReverseProxyServiceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReverseProxyServiceArrayOutput)
}

// ReverseProxyServiceMapInput is an input type that accepts ReverseProxyServiceMap and ReverseProxyServiceMapOutput values.
// You can construct a concrete instance of `ReverseProxyServiceMapInput` via:
//
//	ReverseProxyServiceMap{ "key": ReverseProxyServiceArgs{...} }
type ReverseProxyServiceMapInput interface {
	pulumi.Input

	ToReverseProxyServiceMapOutput() ReverseProxyServiceMapOutput
	ToReverseProxyServiceMapOutputWithContext(context.Context) ReverseProxyServiceMapOutput
}

type ReverseProxyServiceMap map[string]ReverseProxyServiceInput

func (ReverseProxyServiceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReverseProxyService)(nil)).Elem()
}

func (i ReverseProxyServiceMap) ToReverseProxyServiceMapOutput() ReverseProxyServiceMapOutput {
	return i.ToReverseProxyServiceMapOutputWithContext(context.Background())
}

func (i ReverseProxyServiceMap) ToReverseProxyServiceMapOutputWithContext(ctx context.Context) ReverseProxyServiceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReverseProxyServiceMapOutput)
}

type ReverseProxyServiceOutput struct{ *pulumi.OutputState }

func (ReverseProxyServiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ReverseProxyService)(nil)).Elem()
}

func (o ReverseProxyServiceOutput) ToReverseProxyServiceOutput() ReverseProxyServiceOutput {
	return o
}

func (o ReverseProxyServiceOutput) ToReverseProxyServiceOutputWithContext(ctx context.Context) ReverseProxyServiceOutput {
	return o
}

// Domain for the service.
func (o ReverseProxyServiceOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Whether the service is enabled.
func (o ReverseProxyServiceOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Port the proxy listens on (L4/TLS only).
func (o ReverseProxyServiceOutput) ListenPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.IntPtrOutput { return v.ListenPort }).(pulumi.IntPtrOutput)
}

// Service mode: "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough.
func (o ReverseProxyServiceOutput) Mode() ReverseProxyServiceModePtrOutput {
	return o.ApplyT(func(v *ReverseProxyService) ReverseProxyServiceModePtrOutput { return v.Mode }).(ReverseProxyServiceModePtrOutput)
}

// Service name.
func (o ReverseProxyServiceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// When true, the original client Host header is passed through to the backend.
func (o ReverseProxyServiceOutput) PassHostHeader() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.BoolPtrOutput { return v.PassHostHeader }).(pulumi.BoolPtrOutput)
}

// The proxy cluster handling this service (derived from domain).
func (o ReverseProxyServiceOutput) ProxyCluster() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.StringPtrOutput { return v.ProxyCluster }).(pulumi.StringPtrOutput)
}

// When true, Location headers in backend responses are rewritten to the public-facing domain.
func (o ReverseProxyServiceOutput) RewriteRedirects() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.BoolPtrOutput { return v.RewriteRedirects }).(pulumi.BoolPtrOutput)
}

// Current status of the service.
func (o ReverseProxyServiceOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ReverseProxyService) pulumi.StringPtrOutput { return v.Status }).(pulumi.StringPtrOutput)
}

// List of target backends for this service.
func (o ReverseProxyServiceOutput) Targets() ReverseProxyTargetArrayOutput {
	return o.ApplyT(func(v *ReverseProxyService) ReverseProxyTargetArrayOutput { return v.Targets }).(ReverseProxyTargetArrayOutput)
}

type ReverseProxyServiceArrayOutput struct{ *pulumi.OutputState }

func (ReverseProxyServiceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReverseProxyService)(nil)).Elem()
}

func (o ReverseProxyServiceArrayOutput) ToReverseProxyServiceArrayOutput() ReverseProxyServiceArrayOutput {
	return o
}

func (o ReverseProxyServiceArrayOutput) ToReverseProxyServiceArrayOutputWithContext(ctx context.Context) ReverseProxyServiceArrayOutput {
	return o
}

func (o ReverseProxyServiceArrayOutput) Index(i pulumi.IntInput) ReverseProxyServiceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ReverseProxyService {
		return vs[0].([]*ReverseProxyService)[vs[1].(int)]
	}).(ReverseProxyServiceOutput)
}

type ReverseProxyServiceMapOutput struct{ *pulumi.OutputState }

func (ReverseProxyServiceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReverseProxyService)(nil)).Elem()
}

func (o ReverseProxyServiceMapOutput) ToReverseProxyServiceMapOutput() ReverseProxyServiceMapOutput {
	return o
}

func (o ReverseProxyServiceMapOutput) ToReverseProxyServiceMapOutputWithContext(ctx context.Context) ReverseProxyServiceMapOutput {
	return o
}

func (o ReverseProxyServiceMapOutput) MapIndex(k pulumi.StringInput) ReverseProxyServiceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ReverseProxyService {
		return vs[0].(map[string]*ReverseProxyService)[vs[1].(string)]
	}).(ReverseProxyServiceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ReverseProxyServiceInput)(nil)).Elem(), &ReverseProxyService{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReverseProxyServiceArrayInput)(nil)).Elem(), ReverseProxyServiceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReverseProxyServiceMapInput)(nil)).Elem(), ReverseProxyServiceMap{})
	pulumi.RegisterOutputType(ReverseProxyServiceOutput{})
	pulumi.RegisterOutputType(ReverseProxyServiceArrayOutput{})
	pulumi.RegisterOutputType(ReverseProxyServiceMapOutput{})
}
