// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resource

import (
	"context"
	"reflect"

	"errors"
	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A NetBird reverse proxy custom domain.
type ReverseProxyDomain struct {
	pulumi.CustomResourceState

	// Domain name for the reverse proxy.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Whether a subdomain label is required in front of this domain.
	RequireSubdomain pulumi.BoolPtrOutput `pulumi:"requireSubdomain"`
	// Whether the cluster supports binding arbitrary TCP/UDP ports.
	SupportsCustomPorts pulumi.BoolPtrOutput `pulumi:"supportsCustomPorts"`
	// The proxy cluster this domain is validated against.
	TargetCluster pulumi.StringOutput `pulumi:"targetCluster"`
	// Type of the reverse proxy domain (custom or free).
	Type ReverseProxyDomainTypeOutput `pulumi:"type"`
	// Whether the domain has been validated.
	Validated pulumi.BoolOutput `pulumi:"validated"`
}

// NewReverseProxyDomain registers a new resource with the given unique name, arguments, and options.
func NewReverseProxyDomain(ctx *pulumi.Context,
	name string, args *ReverseProxyDomainArgs, opts ...pulumi.ResourceOption) (*ReverseProxyDomain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.TargetCluster == nil {
		return nil, errors.New("invalid value for required argument 'TargetCluster'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ReverseProxyDomain
	err := ctx.RegisterResource("netbird:resource:ReverseProxyDomain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetReverseProxyDomain gets an existing ReverseProxyDomain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetReverseProxyDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ReverseProxyDomainState, opts ...pulumi.ResourceOption) (*ReverseProxyDomain, error) {
	var resource ReverseProxyDomain
	err := ctx.ReadResource("netbird:resource:ReverseProxyDomain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ReverseProxyDomain resources.
type reverseProxyDomainState struct {
}

type ReverseProxyDomainState struct {
}

func (ReverseProxyDomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*reverseProxyDomainState)(nil)).Elem()
}

type reverseProxyDomainArgs struct {
	// Domain name for the reverse proxy.
	Domain string `pulumi:"domain"`
	// The proxy cluster this domain should be validated against.
	TargetCluster string `pulumi:"targetCluster"`
}

// The set of arguments for constructing a ReverseProxyDomain resource.
type ReverseProxyDomainArgs struct {
	// Domain name for the reverse proxy.
	Domain pulumi.StringInput
	// The proxy cluster this domain should be validated against.
	TargetCluster pulumi.StringInput
}

func (ReverseProxyDomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*reverseProxyDomainArgs)(nil)).Elem()
}

type ReverseProxyDomainInput interface {
	pulumi.Input

	ToReverseProxyDomainOutput() ReverseProxyDomainOutput
	ToReverseProxyDomainOutputWithContext(ctx context.Context) ReverseProxyDomainOutput
}

func (*ReverseProxyDomain) ElementType() reflect.Type {
	return reflect.TypeOf((**ReverseProxyDomain)(nil)).Elem()
}

func (i *ReverseProxyDomain) ToReverseProxyDomainOutput() ReverseProxyDomainOutput {
	return i.ToReverseProxyDomainOutputWithContext(context.Background())
}

func (i *ReverseProxyDomain) ToReverseProxyDomainOutputWithContext(ctx context.Context) ReverseProxyDomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReverseProxyDomainOutput)
}

// ReverseProxyDomainArrayInput is an input type that accepts ReverseProxyDomainArray and ReverseProxyDomainArrayOutput values.
// You can construct a concrete instance of `ReverseProxyDomainArrayInput` via:
//
//	ReverseProxyDomainArray{ ReverseProxyDomainArgs{...} }
type ReverseProxyDomainArrayInput interface {
	pulumi.Input

	ToReverseProxyDomainArrayOutput() ReverseProxyDomainArrayOutput
	ToReverseProxyDomainArrayOutputWithContext(context.Context) ReverseProxyDomainArrayOutput
}

type ReverseProxyDomainArray []ReverseProxyDomainInput

func (ReverseProxyDomainArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReverseProxyDomain)(nil)).Elem()
}

func (i ReverseProxyDomainArray) ToReverseProxyDomainArrayOutput() ReverseProxyDomainArrayOutput {
	return i.ToReverseProxyDomainArrayOutputWithContext(context.Background())
}

func (i ReverseProxyDomainArray) ToReverseProxyDomainArrayOutputWithContext(ctx context.Context) ReverseProxyDomainArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReverseProxyDomainArrayOutput)
}

// ReverseProxyDomainMapInput is an input type that accepts ReverseProxyDomainMap and ReverseProxyDomainMapOutput values.
// You can construct a concrete instance of `ReverseProxyDomainMapInput` via:
//
//	ReverseProxyDomainMap{ "key": ReverseProxyDomainArgs{...} }
type ReverseProxyDomainMapInput interface {
	pulumi.Input

	ToReverseProxyDomainMapOutput() ReverseProxyDomainMapOutput
	ToReverseProxyDomainMapOutputWithContext(context.Context) ReverseProxyDomainMapOutput
}

type ReverseProxyDomainMap map[string]ReverseProxyDomainInput

func (ReverseProxyDomainMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReverseProxyDomain)(nil)).Elem()
}

func (i ReverseProxyDomainMap) ToReverseProxyDomainMapOutput() ReverseProxyDomainMapOutput {
	return i.ToReverseProxyDomainMapOutputWithContext(context.Background())
}

func (i ReverseProxyDomainMap) ToReverseProxyDomainMapOutputWithContext(ctx context.Context) ReverseProxyDomainMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReverseProxyDomainMapOutput)
}

type ReverseProxyDomainOutput struct{ *pulumi.OutputState }

func (ReverseProxyDomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ReverseProxyDomain)(nil)).Elem()
}

func (o ReverseProxyDomainOutput) ToReverseProxyDomainOutput() ReverseProxyDomainOutput {
	return o
}

func (o ReverseProxyDomainOutput) ToReverseProxyDomainOutputWithContext(ctx context.Context) ReverseProxyDomainOutput {
	return o
}

// Domain name for the reverse proxy.
func (o ReverseProxyDomainOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *ReverseProxyDomain) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Whether a subdomain label is required in front of this domain.
func (o ReverseProxyDomainOutput) RequireSubdomain() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ReverseProxyDomain) pulumi.BoolPtrOutput { return v.RequireSubdomain }).(pulumi.BoolPtrOutput)
}

// Whether the cluster supports binding arbitrary TCP/UDP ports.
func (o ReverseProxyDomainOutput) SupportsCustomPorts() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ReverseProxyDomain) pulumi.BoolPtrOutput { return v.SupportsCustomPorts }).(pulumi.BoolPtrOutput)
}

// The proxy cluster this domain is validated against.
func (o ReverseProxyDomainOutput) TargetCluster() pulumi.StringOutput {
	return o.ApplyT(func(v *ReverseProxyDomain) pulumi.StringOutput { return v.TargetCluster }).(pulumi.StringOutput)
}

// Type of the reverse proxy domain (custom or free).
func (o ReverseProxyDomainOutput) Type() ReverseProxyDomainTypeOutput {
	return o.ApplyT(func(v *ReverseProxyDomain) ReverseProxyDomainTypeOutput { return v.Type }).(ReverseProxyDomainTypeOutput)
}

// Whether the domain has been validated.
func (o ReverseProxyDomainOutput) Validated() pulumi.BoolOutput {
	return o.ApplyT(func(v *ReverseProxyDomain) pulumi.BoolOutput { return v.Validated }).(pulumi.BoolOutput)
}

type ReverseProxyDomainArrayOutput struct{ *pulumi.OutputState }

func (ReverseProxyDomainArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReverseProxyDomain)(nil)).Elem()
}

func (o ReverseProxyDomainArrayOutput) ToReverseProxyDomainArrayOutput() ReverseProxyDomainArrayOutput {
	return o
}

func (o ReverseProxyDomainArrayOutput) ToReverseProxyDomainArrayOutputWithContext(ctx context.Context) ReverseProxyDomainArrayOutput {
	return o
}

func (o ReverseProxyDomainArrayOutput) Index(i pulumi.IntInput) ReverseProxyDomainOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ReverseProxyDomain {
		return vs[0].([]*ReverseProxyDomain)[vs[1].(int)]
	}).(ReverseProxyDomainOutput)
}

type ReverseProxyDomainMapOutput struct{ *pulumi.OutputState }

func (ReverseProxyDomainMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReverseProxyDomain)(nil)).Elem()
}

func (o ReverseProxyDomainMapOutput) ToReverseProxyDomainMapOutput() ReverseProxyDomainMapOutput {
	return o
}

func (o ReverseProxyDomainMapOutput) ToReverseProxyDomainMapOutputWithContext(ctx context.Context) ReverseProxyDomainMapOutput {
	return o
}

func (o ReverseProxyDomainMapOutput) MapIndex(k pulumi.StringInput) ReverseProxyDomainOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ReverseProxyDomain {
		return vs[0].(map[string]*ReverseProxyDomain)[vs[1].(string)]
	}).(ReverseProxyDomainOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ReverseProxyDomainInput)(nil)).Elem(), &ReverseProxyDomain{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReverseProxyDomainArrayInput)(nil)).Elem(), ReverseProxyDomainArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReverseProxyDomainMapInput)(nil)).Elem(), ReverseProxyDomainMap{})
	pulumi.RegisterOutputType(ReverseProxyDomainOutput{})
	pulumi.RegisterOutputType(ReverseProxyDomainArrayOutput{})
	pulumi.RegisterOutputType(ReverseProxyDomainMapOutput{})
}
