// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// List the catalog of upstream AI providers supported by NetBird Agent Network, with their default models and pricing. Useful for looking up a providerId and model ids for AgentNetworkProvider.
func GetAgentNetworkCatalogProviders(ctx *pulumi.Context, args *GetAgentNetworkCatalogProvidersArgs, opts ...pulumi.InvokeOption) (*GetAgentNetworkCatalogProvidersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAgentNetworkCatalogProvidersResult
	err := ctx.Invoke("netbird:function:getAgentNetworkCatalogProviders", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAgentNetworkCatalogProvidersArgs struct {
}

type GetAgentNetworkCatalogProvidersResult struct {
	// The list of catalog providers.
	Providers []AgentNetworkCatalogProviderEntry `pulumi:"providers"`
}

func GetAgentNetworkCatalogProvidersOutput(ctx *pulumi.Context, args GetAgentNetworkCatalogProvidersOutputArgs, opts ...pulumi.InvokeOption) GetAgentNetworkCatalogProvidersResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("netbird:function:getAgentNetworkCatalogProviders", args, GetAgentNetworkCatalogProvidersResultOutput{}, options).(GetAgentNetworkCatalogProvidersResultOutput)
}

type GetAgentNetworkCatalogProvidersOutputArgs struct {
}

func (GetAgentNetworkCatalogProvidersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAgentNetworkCatalogProvidersArgs)(nil)).Elem()
}

type GetAgentNetworkCatalogProvidersResultOutput struct{ *pulumi.OutputState }

func (GetAgentNetworkCatalogProvidersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAgentNetworkCatalogProvidersResult)(nil)).Elem()
}

func (o GetAgentNetworkCatalogProvidersResultOutput) ToGetAgentNetworkCatalogProvidersResultOutput() GetAgentNetworkCatalogProvidersResultOutput {
	return o
}

func (o GetAgentNetworkCatalogProvidersResultOutput) ToGetAgentNetworkCatalogProvidersResultOutputWithContext(ctx context.Context) GetAgentNetworkCatalogProvidersResultOutput {
	return o
}

// The list of catalog providers.
func (o GetAgentNetworkCatalogProvidersResultOutput) Providers() AgentNetworkCatalogProviderEntryArrayOutput {
	return o.ApplyT(func(v GetAgentNetworkCatalogProvidersResult) []AgentNetworkCatalogProviderEntry { return v.Providers }).(AgentNetworkCatalogProviderEntryArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAgentNetworkCatalogProvidersResultOutput{})
}
