// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// List the cities within a country from NetBird's geo-location database. Useful for populating PostureCheck geo-location rules with specific cities.
func GetCountryCities(ctx *pulumi.Context, args *GetCountryCitiesArgs, opts ...pulumi.InvokeOption) (*GetCountryCitiesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCountryCitiesResult
	err := ctx.Invoke("netbird:function:getCountryCities", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetCountryCitiesArgs struct {
	// 2-letter ISO 3166-1 alpha-2 country code to list cities for.
	CountryCode string `pulumi:"countryCode"`
}

type GetCountryCitiesResult struct {
	// The list of cities in the country.
	Cities []City `pulumi:"cities"`
}

func GetCountryCitiesOutput(ctx *pulumi.Context, args GetCountryCitiesOutputArgs, opts ...pulumi.InvokeOption) GetCountryCitiesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetCountryCitiesResultOutput, error) {
			args := v.(GetCountryCitiesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:function:getCountryCities", args, GetCountryCitiesResultOutput{}, options).(GetCountryCitiesResultOutput), nil
		}).(GetCountryCitiesResultOutput)
}

type GetCountryCitiesOutputArgs struct {
	// 2-letter ISO 3166-1 alpha-2 country code to list cities for.
	CountryCode pulumi.StringInput `pulumi:"countryCode"`
}

func (GetCountryCitiesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCountryCitiesArgs)(nil)).Elem()
}

type GetCountryCitiesResultOutput struct{ *pulumi.OutputState }

func (GetCountryCitiesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCountryCitiesResult)(nil)).Elem()
}

func (o GetCountryCitiesResultOutput) ToGetCountryCitiesResultOutput() GetCountryCitiesResultOutput {
	return o
}

func (o GetCountryCitiesResultOutput) ToGetCountryCitiesResultOutputWithContext(ctx context.Context) GetCountryCitiesResultOutput {
	return o
}

// The list of cities in the country.
func (o GetCountryCitiesResultOutput) Cities() CityArrayOutput {
	return o.ApplyT(func(v GetCountryCitiesResult) []City { return v.Cities }).(CityArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCountryCitiesResultOutput{})
}
