// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// List all countries known to NetBird's geo-location database. Useful for populating PostureCheck geo-location rules.
func GetCountries(ctx *pulumi.Context, args *GetCountriesArgs, opts ...pulumi.InvokeOption) (*GetCountriesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCountriesResult
	err := ctx.Invoke("netbird:function:getCountries", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetCountriesArgs struct {
}

type GetCountriesResult struct {
	// The list of countries.
	Countries []Country `pulumi:"countries"`
}

func GetCountriesOutput(ctx *pulumi.Context, args GetCountriesOutputArgs, opts ...pulumi.InvokeOption) GetCountriesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetCountriesResultOutput, error) {
			args := v.(GetCountriesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:function:getCountries", args, GetCountriesResultOutput{}, options).(GetCountriesResultOutput), nil
		}).(GetCountriesResultOutput)
}

type GetCountriesOutputArgs struct {
}

func (GetCountriesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCountriesArgs)(nil)).Elem()
}

type GetCountriesResultOutput struct{ *pulumi.OutputState }

func (GetCountriesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCountriesResult)(nil)).Elem()
}

func (o GetCountriesResultOutput) ToGetCountriesResultOutput() GetCountriesResultOutput {
	return o
}

func (o GetCountriesResultOutput) ToGetCountriesResultOutputWithContext(ctx context.Context) GetCountriesResultOutput {
	return o
}

// The list of countries.
func (o GetCountriesResultOutput) Countries() CountryArrayOutput {
	return o.ApplyT(func(v GetCountriesResult) []Country { return v.Countries }).(CountryArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCountriesResultOutput{})
}
