// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// List all NetBird reverse proxy clusters. Clusters are auto-provisioned server-side (there is no create endpoint); use this to discover a cluster address to pin a ReverseProxyDomain against via its targetCluster input.
func GetReverseProxyClusters(ctx *pulumi.Context, args *GetReverseProxyClustersArgs, opts ...pulumi.InvokeOption) (*GetReverseProxyClustersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetReverseProxyClustersResult
	err := ctx.Invoke("netbird:function:getReverseProxyClusters", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetReverseProxyClustersArgs struct {
	// Optional cluster type filter: 'account' (owned/operated by the account, BYOP) or 'shared' (operated by NetBird and shared across accounts). When set, only clusters of this type are returned.
	Type *string `pulumi:"type"`
}

type GetReverseProxyClustersResult struct {
	// The list of reverse proxy clusters matching the filter criteria.
	Clusters []ProxyClusterSummary `pulumi:"clusters"`
}

func GetReverseProxyClustersOutput(ctx *pulumi.Context, args GetReverseProxyClustersOutputArgs, opts ...pulumi.InvokeOption) GetReverseProxyClustersResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetReverseProxyClustersResultOutput, error) {
			args := v.(GetReverseProxyClustersArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:function:getReverseProxyClusters", args, GetReverseProxyClustersResultOutput{}, options).(GetReverseProxyClustersResultOutput), nil
		}).(GetReverseProxyClustersResultOutput)
}

type GetReverseProxyClustersOutputArgs struct {
	// Optional cluster type filter: 'account' (owned/operated by the account, BYOP) or 'shared' (operated by NetBird and shared across accounts). When set, only clusters of this type are returned.
	Type pulumi.StringPtrInput `pulumi:"type"`
}

func (GetReverseProxyClustersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetReverseProxyClustersArgs)(nil)).Elem()
}

type GetReverseProxyClustersResultOutput struct{ *pulumi.OutputState }

func (GetReverseProxyClustersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetReverseProxyClustersResult)(nil)).Elem()
}

func (o GetReverseProxyClustersResultOutput) ToGetReverseProxyClustersResultOutput() GetReverseProxyClustersResultOutput {
	return o
}

func (o GetReverseProxyClustersResultOutput) ToGetReverseProxyClustersResultOutputWithContext(ctx context.Context) GetReverseProxyClustersResultOutput {
	return o
}

// The list of reverse proxy clusters matching the filter criteria.
func (o GetReverseProxyClustersResultOutput) Clusters() ProxyClusterSummaryArrayOutput {
	return o.ApplyT(func(v GetReverseProxyClustersResult) []ProxyClusterSummary { return v.Clusters }).(ProxyClusterSummaryArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetReverseProxyClustersResultOutput{})
}
