// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Look up an existing NetBird setup key by name and return its metadata (not the secret key value).
func LookupSetupKey(ctx *pulumi.Context, args *LookupSetupKeyArgs, opts ...pulumi.InvokeOption) (*LookupSetupKeyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSetupKeyResult
	err := ctx.Invoke("netbird:function:lookupSetupKey", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupSetupKeyArgs struct {
	// The name of the setup key to look up.
	Name string `pulumi:"name"`
}

type LookupSetupKeyResult struct {
	// Group IDs automatically assigned to peers that register with this key.
	AutoGroups []string `pulumi:"autoGroups"`
	// Whether peers registered with this key are ephemeral.
	Ephemeral bool `pulumi:"ephemeral"`
	// Key expiration timestamp in RFC3339 format.
	Expires string `pulumi:"expires"`
	// Timestamp of last key use in RFC3339 format.
	LastUsed string `pulumi:"lastUsed"`
	// The setup key name.
	Name string `pulumi:"name"`
	// Whether the setup key has been revoked.
	Revoked bool `pulumi:"revoked"`
	// The NetBird setup key ID.
	SetupKeyId string `pulumi:"setupKeyId"`
	// The setup key state: 'valid', 'overused', 'expired', or 'revoked'.
	State string `pulumi:"state"`
	// The setup key type: 'one-off' or 'reusable'.
	Type string `pulumi:"type"`
	// Maximum number of times the key can be used (0 = unlimited for reusable).
	UsageLimit int `pulumi:"usageLimit"`
}

func LookupSetupKeyOutput(ctx *pulumi.Context, args LookupSetupKeyOutputArgs, opts ...pulumi.InvokeOption) LookupSetupKeyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSetupKeyResultOutput, error) {
			args := v.(LookupSetupKeyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:function:lookupSetupKey", args, LookupSetupKeyResultOutput{}, options).(LookupSetupKeyResultOutput), nil
		}).(LookupSetupKeyResultOutput)
}

type LookupSetupKeyOutputArgs struct {
	// The name of the setup key to look up.
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupSetupKeyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSetupKeyArgs)(nil)).Elem()
}

type LookupSetupKeyResultOutput struct{ *pulumi.OutputState }

func (LookupSetupKeyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSetupKeyResult)(nil)).Elem()
}

func (o LookupSetupKeyResultOutput) ToLookupSetupKeyResultOutput() LookupSetupKeyResultOutput {
	return o
}

func (o LookupSetupKeyResultOutput) ToLookupSetupKeyResultOutputWithContext(ctx context.Context) LookupSetupKeyResultOutput {
	return o
}

// Group IDs automatically assigned to peers that register with this key.
func (o LookupSetupKeyResultOutput) AutoGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) []string { return v.AutoGroups }).(pulumi.StringArrayOutput)
}

// Whether peers registered with this key are ephemeral.
func (o LookupSetupKeyResultOutput) Ephemeral() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) bool { return v.Ephemeral }).(pulumi.BoolOutput)
}

// Key expiration timestamp in RFC3339 format.
func (o LookupSetupKeyResultOutput) Expires() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) string { return v.Expires }).(pulumi.StringOutput)
}

// Timestamp of last key use in RFC3339 format.
func (o LookupSetupKeyResultOutput) LastUsed() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) string { return v.LastUsed }).(pulumi.StringOutput)
}

// The setup key name.
func (o LookupSetupKeyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) string { return v.Name }).(pulumi.StringOutput)
}

// Whether the setup key has been revoked.
func (o LookupSetupKeyResultOutput) Revoked() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) bool { return v.Revoked }).(pulumi.BoolOutput)
}

// The NetBird setup key ID.
func (o LookupSetupKeyResultOutput) SetupKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) string { return v.SetupKeyId }).(pulumi.StringOutput)
}

// The setup key state: 'valid', 'overused', 'expired', or 'revoked'.
func (o LookupSetupKeyResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) string { return v.State }).(pulumi.StringOutput)
}

// The setup key type: 'one-off' or 'reusable'.
func (o LookupSetupKeyResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) string { return v.Type }).(pulumi.StringOutput)
}

// Maximum number of times the key can be used (0 = unlimited for reusable).
func (o LookupSetupKeyResultOutput) UsageLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSetupKeyResult) int { return v.UsageLimit }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSetupKeyResultOutput{})
}
