// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Look up an existing NetBird group by name and return its ID, peer list, and resource list.
func LookupGroup(ctx *pulumi.Context, args *LookupGroupArgs, opts ...pulumi.InvokeOption) (*LookupGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGroupResult
	err := ctx.Invoke("netbird:function:lookupGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupGroupArgs struct {
	// The name of the group to look up.
	Name string `pulumi:"name"`
}

type LookupGroupResult struct {
	// The NetBird group ID.
	GroupId string `pulumi:"groupId"`
	// The group name.
	Name string `pulumi:"name"`
	// IDs of peers belonging to the group.
	Peers []string `pulumi:"peers"`
	// Number of peers in the group.
	PeersCount int `pulumi:"peersCount"`
	// Resources associated with the group.
	Resources []ResourceRef `pulumi:"resources"`
	// Number of resources in the group.
	ResourcesCount int `pulumi:"resourcesCount"`
}

func LookupGroupOutput(ctx *pulumi.Context, args LookupGroupOutputArgs, opts ...pulumi.InvokeOption) LookupGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupGroupResultOutput, error) {
			args := v.(LookupGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:function:lookupGroup", args, LookupGroupResultOutput{}, options).(LookupGroupResultOutput), nil
		}).(LookupGroupResultOutput)
}

type LookupGroupOutputArgs struct {
	// The name of the group to look up.
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGroupArgs)(nil)).Elem()
}

type LookupGroupResultOutput struct{ *pulumi.OutputState }

func (LookupGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGroupResult)(nil)).Elem()
}

func (o LookupGroupResultOutput) ToLookupGroupResultOutput() LookupGroupResultOutput {
	return o
}

func (o LookupGroupResultOutput) ToLookupGroupResultOutputWithContext(ctx context.Context) LookupGroupResultOutput {
	return o
}

// The NetBird group ID.
func (o LookupGroupResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.GroupId }).(pulumi.StringOutput)
}

// The group name.
func (o LookupGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

// IDs of peers belonging to the group.
func (o LookupGroupResultOutput) Peers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []string { return v.Peers }).(pulumi.StringArrayOutput)
}

// Number of peers in the group.
func (o LookupGroupResultOutput) PeersCount() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGroupResult) int { return v.PeersCount }).(pulumi.IntOutput)
}

// Resources associated with the group.
func (o LookupGroupResultOutput) Resources() ResourceRefArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []ResourceRef { return v.Resources }).(ResourceRefArrayOutput)
}

// Number of resources in the group.
func (o LookupGroupResultOutput) ResourcesCount() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGroupResult) int { return v.ResourcesCount }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGroupResultOutput{})
}
