// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Look up an existing NetBird route by network CIDR and return its ID, routing peers, and configuration.
func LookupRoute(ctx *pulumi.Context, args *LookupRouteArgs, opts ...pulumi.InvokeOption) (*LookupRouteResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupRouteResult
	err := ctx.Invoke("netbird:function:lookupRoute", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupRouteArgs struct {
	// The network CIDR (e.g. '10.0.0.0/8') to look up. Returns the first matching route.
	Network string `pulumi:"network"`
}

type LookupRouteResult struct {
	// The route description.
	Description string `pulumi:"description"`
	// Domain list for dynamic resolution (if this is a domain route).
	Domains []string `pulumi:"domains"`
	// Whether the route is enabled.
	Enabled bool `pulumi:"enabled"`
	// Group IDs that have access to this route.
	Groups []string `pulumi:"groups"`
	// Whether the routing peer masquerades traffic to this prefix.
	Masquerade bool `pulumi:"masquerade"`
	// Route metric; lower number means higher priority.
	Metric int `pulumi:"metric"`
	// The network CIDR range.
	Network string `pulumi:"network"`
	// The peer ID acting as the routing peer (mutually exclusive with peerGroups).
	Peer *string `pulumi:"peer"`
	// Group IDs whose peers act as routing peers (mutually exclusive with peer).
	PeerGroups []string `pulumi:"peerGroups"`
	// The NetBird route ID.
	RouteId string `pulumi:"routeId"`
}

func LookupRouteOutput(ctx *pulumi.Context, args LookupRouteOutputArgs, opts ...pulumi.InvokeOption) LookupRouteResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupRouteResultOutput, error) {
			args := v.(LookupRouteArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:function:lookupRoute", args, LookupRouteResultOutput{}, options).(LookupRouteResultOutput), nil
		}).(LookupRouteResultOutput)
}

type LookupRouteOutputArgs struct {
	// The network CIDR (e.g. '10.0.0.0/8') to look up. Returns the first matching route.
	Network pulumi.StringInput `pulumi:"network"`
}

func (LookupRouteOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRouteArgs)(nil)).Elem()
}

type LookupRouteResultOutput struct{ *pulumi.OutputState }

func (LookupRouteResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRouteResult)(nil)).Elem()
}

func (o LookupRouteResultOutput) ToLookupRouteResultOutput() LookupRouteResultOutput {
	return o
}

func (o LookupRouteResultOutput) ToLookupRouteResultOutputWithContext(ctx context.Context) LookupRouteResultOutput {
	return o
}

// The route description.
func (o LookupRouteResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouteResult) string { return v.Description }).(pulumi.StringOutput)
}

// Domain list for dynamic resolution (if this is a domain route).
func (o LookupRouteResultOutput) Domains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupRouteResult) []string { return v.Domains }).(pulumi.StringArrayOutput)
}

// Whether the route is enabled.
func (o LookupRouteResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupRouteResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Group IDs that have access to this route.
func (o LookupRouteResultOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupRouteResult) []string { return v.Groups }).(pulumi.StringArrayOutput)
}

// Whether the routing peer masquerades traffic to this prefix.
func (o LookupRouteResultOutput) Masquerade() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupRouteResult) bool { return v.Masquerade }).(pulumi.BoolOutput)
}

// Route metric; lower number means higher priority.
func (o LookupRouteResultOutput) Metric() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRouteResult) int { return v.Metric }).(pulumi.IntOutput)
}

// The network CIDR range.
func (o LookupRouteResultOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouteResult) string { return v.Network }).(pulumi.StringOutput)
}

// The peer ID acting as the routing peer (mutually exclusive with peerGroups).
func (o LookupRouteResultOutput) Peer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupRouteResult) *string { return v.Peer }).(pulumi.StringPtrOutput)
}

// Group IDs whose peers act as routing peers (mutually exclusive with peer).
func (o LookupRouteResultOutput) PeerGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupRouteResult) []string { return v.PeerGroups }).(pulumi.StringArrayOutput)
}

// The NetBird route ID.
func (o LookupRouteResultOutput) RouteId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouteResult) string { return v.RouteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRouteResultOutput{})
}
