// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package function

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type City struct {
	// Commonly used English name of the city.
	CityName string `pulumi:"cityName"`
	// Integer ID of the record in the GeoNames database.
	GeonameId int `pulumi:"geonameId"`
}

type CityOutput struct{ *pulumi.OutputState }

func (CityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*City)(nil)).Elem()
}

func (o CityOutput) ToCityOutput() CityOutput {
	return o
}

func (o CityOutput) ToCityOutputWithContext(ctx context.Context) CityOutput {
	return o
}

// Commonly used English name of the city.
func (o CityOutput) CityName() pulumi.StringOutput {
	return o.ApplyT(func(v City) string { return v.CityName }).(pulumi.StringOutput)
}

// Integer ID of the record in the GeoNames database.
func (o CityOutput) GeonameId() pulumi.IntOutput {
	return o.ApplyT(func(v City) int { return v.GeonameId }).(pulumi.IntOutput)
}

type CityArrayOutput struct{ *pulumi.OutputState }

func (CityArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]City)(nil)).Elem()
}

func (o CityArrayOutput) ToCityArrayOutput() CityArrayOutput {
	return o
}

func (o CityArrayOutput) ToCityArrayOutputWithContext(ctx context.Context) CityArrayOutput {
	return o
}

func (o CityArrayOutput) Index(i pulumi.IntInput) CityOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) City {
		return vs[0].([]City)[vs[1].(int)]
	}).(CityOutput)
}

type Country struct {
	// 2-letter ISO 3166-1 alpha-2 country code.
	CountryCode string `pulumi:"countryCode"`
	// Commonly used English name of the country.
	CountryName string `pulumi:"countryName"`
}

type CountryOutput struct{ *pulumi.OutputState }

func (CountryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Country)(nil)).Elem()
}

func (o CountryOutput) ToCountryOutput() CountryOutput {
	return o
}

func (o CountryOutput) ToCountryOutputWithContext(ctx context.Context) CountryOutput {
	return o
}

// 2-letter ISO 3166-1 alpha-2 country code.
func (o CountryOutput) CountryCode() pulumi.StringOutput {
	return o.ApplyT(func(v Country) string { return v.CountryCode }).(pulumi.StringOutput)
}

// Commonly used English name of the country.
func (o CountryOutput) CountryName() pulumi.StringOutput {
	return o.ApplyT(func(v Country) string { return v.CountryName }).(pulumi.StringOutput)
}

type CountryArrayOutput struct{ *pulumi.OutputState }

func (CountryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Country)(nil)).Elem()
}

func (o CountryArrayOutput) ToCountryArrayOutput() CountryArrayOutput {
	return o
}

func (o CountryArrayOutput) ToCountryArrayOutputWithContext(ctx context.Context) CountryArrayOutput {
	return o
}

func (o CountryArrayOutput) Index(i pulumi.IntInput) CountryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Country {
		return vs[0].([]Country)[vs[1].(int)]
	}).(CountryOutput)
}

type PeerSummary struct {
	// Whether the peer is currently connected to the management server.
	Connected bool `pulumi:"connected"`
	// The DNS label used to form the peer's FQDN.
	DnsLabel string `pulumi:"dnsLabel"`
	// IDs of groups the peer belongs to.
	Groups []string `pulumi:"groups"`
	// The OS hostname of the machine.
	Hostname string `pulumi:"hostname"`
	// The peer ID.
	Id string `pulumi:"id"`
	// The WireGuard IP address assigned to the peer.
	Ip string `pulumi:"ip"`
	// The peer name.
	Name string `pulumi:"name"`
}

type PeerSummaryOutput struct{ *pulumi.OutputState }

func (PeerSummaryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PeerSummary)(nil)).Elem()
}

func (o PeerSummaryOutput) ToPeerSummaryOutput() PeerSummaryOutput {
	return o
}

func (o PeerSummaryOutput) ToPeerSummaryOutputWithContext(ctx context.Context) PeerSummaryOutput {
	return o
}

// Whether the peer is currently connected to the management server.
func (o PeerSummaryOutput) Connected() pulumi.BoolOutput {
	return o.ApplyT(func(v PeerSummary) bool { return v.Connected }).(pulumi.BoolOutput)
}

// The DNS label used to form the peer's FQDN.
func (o PeerSummaryOutput) DnsLabel() pulumi.StringOutput {
	return o.ApplyT(func(v PeerSummary) string { return v.DnsLabel }).(pulumi.StringOutput)
}

// IDs of groups the peer belongs to.
func (o PeerSummaryOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v PeerSummary) []string { return v.Groups }).(pulumi.StringArrayOutput)
}

// The OS hostname of the machine.
func (o PeerSummaryOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v PeerSummary) string { return v.Hostname }).(pulumi.StringOutput)
}

// The peer ID.
func (o PeerSummaryOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v PeerSummary) string { return v.Id }).(pulumi.StringOutput)
}

// The WireGuard IP address assigned to the peer.
func (o PeerSummaryOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v PeerSummary) string { return v.Ip }).(pulumi.StringOutput)
}

// The peer name.
func (o PeerSummaryOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v PeerSummary) string { return v.Name }).(pulumi.StringOutput)
}

type PeerSummaryArrayOutput struct{ *pulumi.OutputState }

func (PeerSummaryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PeerSummary)(nil)).Elem()
}

func (o PeerSummaryArrayOutput) ToPeerSummaryArrayOutput() PeerSummaryArrayOutput {
	return o
}

func (o PeerSummaryArrayOutput) ToPeerSummaryArrayOutputWithContext(ctx context.Context) PeerSummaryArrayOutput {
	return o
}

func (o PeerSummaryArrayOutput) Index(i pulumi.IntInput) PeerSummaryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PeerSummary {
		return vs[0].([]PeerSummary)[vs[1].(int)]
	}).(PeerSummaryOutput)
}

type ProxyClusterSummary struct {
	// Cluster address used for CNAME targets; the value to pass as a ReverseProxyDomain targetCluster.
	Address string `pulumi:"address"`
	// Number of proxy nodes currently connected.
	ConnectedProxies int `pulumi:"connectedProxies"`
	// Unique identifier of the proxy cluster.
	Id string `pulumi:"id"`
	// Whether at least one proxy in the cluster has heartbeated within the active window.
	Online bool `pulumi:"online"`
	// True when at least one connected proxy is embedded in a netbird client and serving over a WireGuard tunnel.
	Private bool `pulumi:"private"`
	// Whether services on this cluster must include a subdomain label.
	RequireSubdomain bool `pulumi:"requireSubdomain"`
	// Whether all active proxies in the cluster have CrowdSec configured.
	SupportsCrowdsec bool `pulumi:"supportsCrowdsec"`
	// Whether the cluster supports binding arbitrary TCP/UDP ports.
	SupportsCustomPorts bool `pulumi:"supportsCustomPorts"`
	// Source of the cluster: 'account' (BYOP) or 'shared' (operated by NetBird).
	Type string `pulumi:"type"`
}

type ProxyClusterSummaryOutput struct{ *pulumi.OutputState }

func (ProxyClusterSummaryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProxyClusterSummary)(nil)).Elem()
}

func (o ProxyClusterSummaryOutput) ToProxyClusterSummaryOutput() ProxyClusterSummaryOutput {
	return o
}

func (o ProxyClusterSummaryOutput) ToProxyClusterSummaryOutputWithContext(ctx context.Context) ProxyClusterSummaryOutput {
	return o
}

// Cluster address used for CNAME targets; the value to pass as a ReverseProxyDomain targetCluster.
func (o ProxyClusterSummaryOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v ProxyClusterSummary) string { return v.Address }).(pulumi.StringOutput)
}

// Number of proxy nodes currently connected.
func (o ProxyClusterSummaryOutput) ConnectedProxies() pulumi.IntOutput {
	return o.ApplyT(func(v ProxyClusterSummary) int { return v.ConnectedProxies }).(pulumi.IntOutput)
}

// Unique identifier of the proxy cluster.
func (o ProxyClusterSummaryOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ProxyClusterSummary) string { return v.Id }).(pulumi.StringOutput)
}

// Whether at least one proxy in the cluster has heartbeated within the active window.
func (o ProxyClusterSummaryOutput) Online() pulumi.BoolOutput {
	return o.ApplyT(func(v ProxyClusterSummary) bool { return v.Online }).(pulumi.BoolOutput)
}

// True when at least one connected proxy is embedded in a netbird client and serving over a WireGuard tunnel.
func (o ProxyClusterSummaryOutput) Private() pulumi.BoolOutput {
	return o.ApplyT(func(v ProxyClusterSummary) bool { return v.Private }).(pulumi.BoolOutput)
}

// Whether services on this cluster must include a subdomain label.
func (o ProxyClusterSummaryOutput) RequireSubdomain() pulumi.BoolOutput {
	return o.ApplyT(func(v ProxyClusterSummary) bool { return v.RequireSubdomain }).(pulumi.BoolOutput)
}

// Whether all active proxies in the cluster have CrowdSec configured.
func (o ProxyClusterSummaryOutput) SupportsCrowdsec() pulumi.BoolOutput {
	return o.ApplyT(func(v ProxyClusterSummary) bool { return v.SupportsCrowdsec }).(pulumi.BoolOutput)
}

// Whether the cluster supports binding arbitrary TCP/UDP ports.
func (o ProxyClusterSummaryOutput) SupportsCustomPorts() pulumi.BoolOutput {
	return o.ApplyT(func(v ProxyClusterSummary) bool { return v.SupportsCustomPorts }).(pulumi.BoolOutput)
}

// Source of the cluster: 'account' (BYOP) or 'shared' (operated by NetBird).
func (o ProxyClusterSummaryOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v ProxyClusterSummary) string { return v.Type }).(pulumi.StringOutput)
}

type ProxyClusterSummaryArrayOutput struct{ *pulumi.OutputState }

func (ProxyClusterSummaryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ProxyClusterSummary)(nil)).Elem()
}

func (o ProxyClusterSummaryArrayOutput) ToProxyClusterSummaryArrayOutput() ProxyClusterSummaryArrayOutput {
	return o
}

func (o ProxyClusterSummaryArrayOutput) ToProxyClusterSummaryArrayOutputWithContext(ctx context.Context) ProxyClusterSummaryArrayOutput {
	return o
}

func (o ProxyClusterSummaryArrayOutput) Index(i pulumi.IntInput) ProxyClusterSummaryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ProxyClusterSummary {
		return vs[0].([]ProxyClusterSummary)[vs[1].(int)]
	}).(ProxyClusterSummaryOutput)
}

type ResourceRef struct {
	// The unique identifier of the resource.
	Id string `pulumi:"id"`
	// The type of resource: 'domain', 'host', or 'subnet'.
	Type string `pulumi:"type"`
}

type ResourceRefOutput struct{ *pulumi.OutputState }

func (ResourceRefOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceRef)(nil)).Elem()
}

func (o ResourceRefOutput) ToResourceRefOutput() ResourceRefOutput {
	return o
}

func (o ResourceRefOutput) ToResourceRefOutputWithContext(ctx context.Context) ResourceRefOutput {
	return o
}

// The unique identifier of the resource.
func (o ResourceRefOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ResourceRef) string { return v.Id }).(pulumi.StringOutput)
}

// The type of resource: 'domain', 'host', or 'subnet'.
func (o ResourceRefOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v ResourceRef) string { return v.Type }).(pulumi.StringOutput)
}

type ResourceRefArrayOutput struct{ *pulumi.OutputState }

func (ResourceRefArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ResourceRef)(nil)).Elem()
}

func (o ResourceRefArrayOutput) ToResourceRefArrayOutput() ResourceRefArrayOutput {
	return o
}

func (o ResourceRefArrayOutput) ToResourceRefArrayOutputWithContext(ctx context.Context) ResourceRefArrayOutput {
	return o
}

func (o ResourceRefArrayOutput) Index(i pulumi.IntInput) ResourceRefOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ResourceRef {
		return vs[0].([]ResourceRef)[vs[1].(int)]
	}).(ResourceRefOutput)
}

func init() {
	pulumi.RegisterOutputType(CityOutput{})
	pulumi.RegisterOutputType(CityArrayOutput{})
	pulumi.RegisterOutputType(CountryOutput{})
	pulumi.RegisterOutputType(CountryArrayOutput{})
	pulumi.RegisterOutputType(PeerSummaryOutput{})
	pulumi.RegisterOutputType(PeerSummaryArrayOutput{})
	pulumi.RegisterOutputType(ProxyClusterSummaryOutput{})
	pulumi.RegisterOutputType(ProxyClusterSummaryArrayOutput{})
	pulumi.RegisterOutputType(ResourceRefOutput{})
	pulumi.RegisterOutputType(ResourceRefArrayOutput{})
}
