# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import pulumi
from enum import Enum

__all__ = [
    'NameserverNsType',
    'Protocol',
    'RuleAction',
    'Type',
]


@pulumi.type_token("netbird:resource:NameserverNsType")
class NameserverNsType(builtins.str, Enum):
    UDP = "udp"
    """
    UDP type
    """


@pulumi.type_token("netbird:resource:Protocol")
class Protocol(builtins.str, Enum):
    ALL = "all"
    """
    All protocols
    """
    ICMP = "icmp"
    """
    ICMP protocol
    """
    TCP = "tcp"
    """
    TCP protocol
    """
    UDP = "udp"
    """
    UDP protocol
    """


@pulumi.type_token("netbird:resource:RuleAction")
class RuleAction(builtins.str, Enum):
    ACCEPT = "accept"
    """
    Accept action
    """
    DROP = "drop"
    """
    Drop action
    """


@pulumi.type_token("netbird:resource:Type")
class Type(builtins.str, Enum):
    DOMAIN = "domain"
    """
    A domain resource (e.g., example.com).
    """
    HOST = "host"
    """
    A host resource (e.g., peer or device).
    """
    SUBNET = "subnet"
    """
    A subnet resource (e.g., 192.168.0.0/24).
    """
