# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'NameserverArgs',
    'NameserverArgsDict',
    'PolicyRuleArgsArgs',
    'PolicyRuleArgsArgsDict',
    'ResourceArgs',
    'ResourceArgsDict',
    'RulePortRangeArgs',
    'RulePortRangeArgsDict',
]

MYPY = False

if not MYPY:
    class NameserverArgsDict(TypedDict):
        ip: pulumi.Input[builtins.str]
        """
        Ip Nameserver IP
        """
        port: pulumi.Input[builtins.int]
        """
        Port Nameserver Port
        """
        type: pulumi.Input['NameserverNsType']
        """
        NsType Nameserver Type
        """
elif False:
    NameserverArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class NameserverArgs:
    def __init__(__self__, *,
                 ip: pulumi.Input[builtins.str],
                 port: pulumi.Input[builtins.int],
                 type: pulumi.Input['NameserverNsType']):
        """
        :param pulumi.Input[builtins.str] ip: Ip Nameserver IP
        :param pulumi.Input[builtins.int] port: Port Nameserver Port
        :param pulumi.Input['NameserverNsType'] type: NsType Nameserver Type
        """
        pulumi.set(__self__, "ip", ip)
        pulumi.set(__self__, "port", port)
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def ip(self) -> pulumi.Input[builtins.str]:
        """
        Ip Nameserver IP
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "ip", value)

    @property
    @pulumi.getter
    def port(self) -> pulumi.Input[builtins.int]:
        """
        Port Nameserver Port
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: pulumi.Input[builtins.int]):
        pulumi.set(self, "port", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input['NameserverNsType']:
        """
        NsType Nameserver Type
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input['NameserverNsType']):
        pulumi.set(self, "type", value)


if not MYPY:
    class PolicyRuleArgsArgsDict(TypedDict):
        action: pulumi.Input['RuleAction']
        """
        Action Policy rule accept or drops packets
        """
        bidirectional: pulumi.Input[builtins.bool]
        """
        Bidirectional Define if the rule is applicable in both directions, sources, and destinations.
        """
        enabled: pulumi.Input[builtins.bool]
        """
        Enabled Policy rule status
        """
        name: pulumi.Input[builtins.str]
        """
        Name Policy rule name identifier
        """
        protocol: pulumi.Input['Protocol']
        """
        Protocol Policy rule type of the traffic
        """
        description: NotRequired[pulumi.Input[builtins.str]]
        """
        Description Policy rule friendly description
        """
        destination_resource: NotRequired[pulumi.Input['ResourceArgsDict']]
        """
        DestinationResource for the rule 
        """
        destinations: NotRequired[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]
        """
        Destinations Policy rule destination group IDs
        """
        id: NotRequired[pulumi.Input[builtins.str]]
        """
        ID Policy rule.
        """
        port_ranges: NotRequired[pulumi.Input[Sequence[pulumi.Input['RulePortRangeArgsDict']]]]
        """
        PortRanges Policy rule affected ports ranges list
        """
        ports: NotRequired[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]
        """
        Ports Policy rule affected ports
        """
        source_resource: NotRequired[pulumi.Input['ResourceArgsDict']]
        """
        SourceResource for the rule
        """
        sources: NotRequired[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]
        """
        Sources Policy rule source group IDs
        """
elif False:
    PolicyRuleArgsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class PolicyRuleArgsArgs:
    def __init__(__self__, *,
                 action: pulumi.Input['RuleAction'],
                 bidirectional: pulumi.Input[builtins.bool],
                 enabled: pulumi.Input[builtins.bool],
                 name: pulumi.Input[builtins.str],
                 protocol: pulumi.Input['Protocol'],
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 destination_resource: Optional[pulumi.Input['ResourceArgs']] = None,
                 destinations: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 id: Optional[pulumi.Input[builtins.str]] = None,
                 port_ranges: Optional[pulumi.Input[Sequence[pulumi.Input['RulePortRangeArgs']]]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 source_resource: Optional[pulumi.Input['ResourceArgs']] = None,
                 sources: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None):
        """
        :param pulumi.Input['RuleAction'] action: Action Policy rule accept or drops packets
        :param pulumi.Input[builtins.bool] bidirectional: Bidirectional Define if the rule is applicable in both directions, sources, and destinations.
        :param pulumi.Input[builtins.bool] enabled: Enabled Policy rule status
        :param pulumi.Input[builtins.str] name: Name Policy rule name identifier
        :param pulumi.Input['Protocol'] protocol: Protocol Policy rule type of the traffic
        :param pulumi.Input[builtins.str] description: Description Policy rule friendly description
        :param pulumi.Input['ResourceArgs'] destination_resource: DestinationResource for the rule 
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] destinations: Destinations Policy rule destination group IDs
        :param pulumi.Input[builtins.str] id: ID Policy rule.
        :param pulumi.Input[Sequence[pulumi.Input['RulePortRangeArgs']]] port_ranges: PortRanges Policy rule affected ports ranges list
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] ports: Ports Policy rule affected ports
        :param pulumi.Input['ResourceArgs'] source_resource: SourceResource for the rule
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] sources: Sources Policy rule source group IDs
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "bidirectional", bidirectional)
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "protocol", protocol)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if destination_resource is not None:
            pulumi.set(__self__, "destination_resource", destination_resource)
        if destinations is not None:
            pulumi.set(__self__, "destinations", destinations)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if port_ranges is not None:
            pulumi.set(__self__, "port_ranges", port_ranges)
        if ports is not None:
            pulumi.set(__self__, "ports", ports)
        if source_resource is not None:
            pulumi.set(__self__, "source_resource", source_resource)
        if sources is not None:
            pulumi.set(__self__, "sources", sources)

    @property
    @pulumi.getter
    def action(self) -> pulumi.Input['RuleAction']:
        """
        Action Policy rule accept or drops packets
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input['RuleAction']):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def bidirectional(self) -> pulumi.Input[builtins.bool]:
        """
        Bidirectional Define if the rule is applicable in both directions, sources, and destinations.
        """
        return pulumi.get(self, "bidirectional")

    @bidirectional.setter
    def bidirectional(self, value: pulumi.Input[builtins.bool]):
        pulumi.set(self, "bidirectional", value)

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[builtins.bool]:
        """
        Enabled Policy rule status
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[builtins.bool]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[builtins.str]:
        """
        Name Policy rule name identifier
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def protocol(self) -> pulumi.Input['Protocol']:
        """
        Protocol Policy rule type of the traffic
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: pulumi.Input['Protocol']):
        pulumi.set(self, "protocol", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Description Policy rule friendly description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="destinationResource")
    def destination_resource(self) -> Optional[pulumi.Input['ResourceArgs']]:
        """
        DestinationResource for the rule 
        """
        return pulumi.get(self, "destination_resource")

    @destination_resource.setter
    def destination_resource(self, value: Optional[pulumi.Input['ResourceArgs']]):
        pulumi.set(self, "destination_resource", value)

    @property
    @pulumi.getter
    def destinations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        Destinations Policy rule destination group IDs
        """
        return pulumi.get(self, "destinations")

    @destinations.setter
    def destinations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "destinations", value)

    @property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        ID Policy rule.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "id", value)

    @property
    @pulumi.getter(name="portRanges")
    def port_ranges(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['RulePortRangeArgs']]]]:
        """
        PortRanges Policy rule affected ports ranges list
        """
        return pulumi.get(self, "port_ranges")

    @port_ranges.setter
    def port_ranges(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['RulePortRangeArgs']]]]):
        pulumi.set(self, "port_ranges", value)

    @property
    @pulumi.getter
    def ports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        Ports Policy rule affected ports
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "ports", value)

    @property
    @pulumi.getter(name="sourceResource")
    def source_resource(self) -> Optional[pulumi.Input['ResourceArgs']]:
        """
        SourceResource for the rule
        """
        return pulumi.get(self, "source_resource")

    @source_resource.setter
    def source_resource(self, value: Optional[pulumi.Input['ResourceArgs']]):
        pulumi.set(self, "source_resource", value)

    @property
    @pulumi.getter
    def sources(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        Sources Policy rule source group IDs
        """
        return pulumi.get(self, "sources")

    @sources.setter
    def sources(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "sources", value)


if not MYPY:
    class ResourceArgsDict(TypedDict):
        id: pulumi.Input[builtins.str]
        """
        The unique identifier of the resource.
        """
        type: pulumi.Input['ResourceType']
        """
        The type of resource: 'domain', 'host', or 'subnet'.
        """
elif False:
    ResourceArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ResourceArgs:
    def __init__(__self__, *,
                 id: pulumi.Input[builtins.str],
                 type: pulumi.Input['ResourceType']):
        """
        :param pulumi.Input[builtins.str] id: The unique identifier of the resource.
        :param pulumi.Input['ResourceType'] type: The type of resource: 'domain', 'host', or 'subnet'.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def id(self) -> pulumi.Input[builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "id", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input['ResourceType']:
        """
        The type of resource: 'domain', 'host', or 'subnet'.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input['ResourceType']):
        pulumi.set(self, "type", value)


if not MYPY:
    class RulePortRangeArgsDict(TypedDict):
        end: pulumi.Input[builtins.int]
        """
        End of port range
        """
        start: pulumi.Input[builtins.int]
        """
        Start of port range
        """
elif False:
    RulePortRangeArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class RulePortRangeArgs:
    def __init__(__self__, *,
                 end: pulumi.Input[builtins.int],
                 start: pulumi.Input[builtins.int]):
        """
        :param pulumi.Input[builtins.int] end: End of port range
        :param pulumi.Input[builtins.int] start: Start of port range
        """
        pulumi.set(__self__, "end", end)
        pulumi.set(__self__, "start", start)

    @property
    @pulumi.getter
    def end(self) -> pulumi.Input[builtins.int]:
        """
        End of port range
        """
        return pulumi.get(self, "end")

    @end.setter
    def end(self, value: pulumi.Input[builtins.int]):
        pulumi.set(self, "end", value)

    @property
    @pulumi.getter
    def start(self) -> pulumi.Input[builtins.int]:
        """
        Start of port range
        """
        return pulumi.get(self, "start")

    @start.setter
    def start(self, value: pulumi.Input[builtins.int]):
        pulumi.set(self, "start", value)


