// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"context"
	"reflect"

	"github.com/mbrav/pulumi-netbird/sdk/go/netbird/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type PolicyRuleArgs struct {
	// The action to take: 'accept' or 'drop'.
	Action RuleAction `pulumi:"action"`
	// Whether the rule applies bidirectionally.
	Bidirectional bool `pulumi:"bidirectional"`
	// An optional description of the policy rule.
	Description *string `pulumi:"description"`
	// Optional destination resource for the rule.
	DestinationResource *Resource `pulumi:"destinationResource"`
	// Optional list of destination group IDs.
	Destinations []string `pulumi:"destinations"`
	// Whether the rule is active.
	Enabled bool `pulumi:"enabled"`
	// Optional unique identifier for the policy rule.
	Id *string `pulumi:"id"`
	// The name of the policy rule.
	Name string `pulumi:"name"`
	// Optional list of port ranges.
	PortRanges []PolicyRulePortRange `pulumi:"portRanges"`
	// Optional list of ports.
	Ports []string `pulumi:"ports"`
	// The protocol: 'tcp', 'udp', 'icmp', or 'all'.
	Protocol Protocol `pulumi:"protocol"`
	// Optional source resource for the rule.
	SourceResource *Resource `pulumi:"sourceResource"`
	// Optional list of source group IDs.
	Sources []string `pulumi:"sources"`
}

// PolicyRuleArgsInput is an input type that accepts PolicyRuleArgsArgs and PolicyRuleArgsOutput values.
// You can construct a concrete instance of `PolicyRuleArgsInput` via:
//
//	PolicyRuleArgsArgs{...}
type PolicyRuleArgsInput interface {
	pulumi.Input

	ToPolicyRuleArgsOutput() PolicyRuleArgsOutput
	ToPolicyRuleArgsOutputWithContext(context.Context) PolicyRuleArgsOutput
}

type PolicyRuleArgsArgs struct {
	// The action to take: 'accept' or 'drop'.
	Action RuleActionInput `pulumi:"action"`
	// Whether the rule applies bidirectionally.
	Bidirectional pulumi.BoolInput `pulumi:"bidirectional"`
	// An optional description of the policy rule.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Optional destination resource for the rule.
	DestinationResource ResourcePtrInput `pulumi:"destinationResource"`
	// Optional list of destination group IDs.
	Destinations pulumi.StringArrayInput `pulumi:"destinations"`
	// Whether the rule is active.
	Enabled pulumi.BoolInput `pulumi:"enabled"`
	// Optional unique identifier for the policy rule.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the policy rule.
	Name pulumi.StringInput `pulumi:"name"`
	// Optional list of port ranges.
	PortRanges PolicyRulePortRangeArrayInput `pulumi:"portRanges"`
	// Optional list of ports.
	Ports pulumi.StringArrayInput `pulumi:"ports"`
	// The protocol: 'tcp', 'udp', 'icmp', or 'all'.
	Protocol ProtocolInput `pulumi:"protocol"`
	// Optional source resource for the rule.
	SourceResource ResourcePtrInput `pulumi:"sourceResource"`
	// Optional list of source group IDs.
	Sources pulumi.StringArrayInput `pulumi:"sources"`
}

func (PolicyRuleArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PolicyRuleArgs)(nil)).Elem()
}

func (i PolicyRuleArgsArgs) ToPolicyRuleArgsOutput() PolicyRuleArgsOutput {
	return i.ToPolicyRuleArgsOutputWithContext(context.Background())
}

func (i PolicyRuleArgsArgs) ToPolicyRuleArgsOutputWithContext(ctx context.Context) PolicyRuleArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyRuleArgsOutput)
}

// PolicyRuleArgsArrayInput is an input type that accepts PolicyRuleArgsArray and PolicyRuleArgsArrayOutput values.
// You can construct a concrete instance of `PolicyRuleArgsArrayInput` via:
//
//	PolicyRuleArgsArray{ PolicyRuleArgsArgs{...} }
type PolicyRuleArgsArrayInput interface {
	pulumi.Input

	ToPolicyRuleArgsArrayOutput() PolicyRuleArgsArrayOutput
	ToPolicyRuleArgsArrayOutputWithContext(context.Context) PolicyRuleArgsArrayOutput
}

type PolicyRuleArgsArray []PolicyRuleArgsInput

func (PolicyRuleArgsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PolicyRuleArgs)(nil)).Elem()
}

func (i PolicyRuleArgsArray) ToPolicyRuleArgsArrayOutput() PolicyRuleArgsArrayOutput {
	return i.ToPolicyRuleArgsArrayOutputWithContext(context.Background())
}

func (i PolicyRuleArgsArray) ToPolicyRuleArgsArrayOutputWithContext(ctx context.Context) PolicyRuleArgsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyRuleArgsArrayOutput)
}

type PolicyRuleArgsOutput struct{ *pulumi.OutputState }

func (PolicyRuleArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PolicyRuleArgs)(nil)).Elem()
}

func (o PolicyRuleArgsOutput) ToPolicyRuleArgsOutput() PolicyRuleArgsOutput {
	return o
}

func (o PolicyRuleArgsOutput) ToPolicyRuleArgsOutputWithContext(ctx context.Context) PolicyRuleArgsOutput {
	return o
}

// The action to take: 'accept' or 'drop'.
func (o PolicyRuleArgsOutput) Action() RuleActionOutput {
	return o.ApplyT(func(v PolicyRuleArgs) RuleAction { return v.Action }).(RuleActionOutput)
}

// Whether the rule applies bidirectionally.
func (o PolicyRuleArgsOutput) Bidirectional() pulumi.BoolOutput {
	return o.ApplyT(func(v PolicyRuleArgs) bool { return v.Bidirectional }).(pulumi.BoolOutput)
}

// An optional description of the policy rule.
func (o PolicyRuleArgsOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PolicyRuleArgs) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Optional destination resource for the rule.
func (o PolicyRuleArgsOutput) DestinationResource() ResourcePtrOutput {
	return o.ApplyT(func(v PolicyRuleArgs) *Resource { return v.DestinationResource }).(ResourcePtrOutput)
}

// Optional list of destination group IDs.
func (o PolicyRuleArgsOutput) Destinations() pulumi.StringArrayOutput {
	return o.ApplyT(func(v PolicyRuleArgs) []string { return v.Destinations }).(pulumi.StringArrayOutput)
}

// Whether the rule is active.
func (o PolicyRuleArgsOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v PolicyRuleArgs) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Optional unique identifier for the policy rule.
func (o PolicyRuleArgsOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PolicyRuleArgs) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The name of the policy rule.
func (o PolicyRuleArgsOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v PolicyRuleArgs) string { return v.Name }).(pulumi.StringOutput)
}

// Optional list of port ranges.
func (o PolicyRuleArgsOutput) PortRanges() PolicyRulePortRangeArrayOutput {
	return o.ApplyT(func(v PolicyRuleArgs) []PolicyRulePortRange { return v.PortRanges }).(PolicyRulePortRangeArrayOutput)
}

// Optional list of ports.
func (o PolicyRuleArgsOutput) Ports() pulumi.StringArrayOutput {
	return o.ApplyT(func(v PolicyRuleArgs) []string { return v.Ports }).(pulumi.StringArrayOutput)
}

// The protocol: 'tcp', 'udp', 'icmp', or 'all'.
func (o PolicyRuleArgsOutput) Protocol() ProtocolOutput {
	return o.ApplyT(func(v PolicyRuleArgs) Protocol { return v.Protocol }).(ProtocolOutput)
}

// Optional source resource for the rule.
func (o PolicyRuleArgsOutput) SourceResource() ResourcePtrOutput {
	return o.ApplyT(func(v PolicyRuleArgs) *Resource { return v.SourceResource }).(ResourcePtrOutput)
}

// Optional list of source group IDs.
func (o PolicyRuleArgsOutput) Sources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v PolicyRuleArgs) []string { return v.Sources }).(pulumi.StringArrayOutput)
}

type PolicyRuleArgsArrayOutput struct{ *pulumi.OutputState }

func (PolicyRuleArgsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PolicyRuleArgs)(nil)).Elem()
}

func (o PolicyRuleArgsArrayOutput) ToPolicyRuleArgsArrayOutput() PolicyRuleArgsArrayOutput {
	return o
}

func (o PolicyRuleArgsArrayOutput) ToPolicyRuleArgsArrayOutputWithContext(ctx context.Context) PolicyRuleArgsArrayOutput {
	return o
}

func (o PolicyRuleArgsArrayOutput) Index(i pulumi.IntInput) PolicyRuleArgsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PolicyRuleArgs {
		return vs[0].([]PolicyRuleArgs)[vs[1].(int)]
	}).(PolicyRuleArgsOutput)
}

type PolicyRuleGroup struct {
	// The unique identifier of the group.
	Id string `pulumi:"id"`
	// The name of the group.
	Name string `pulumi:"name"`
}

type PolicyRuleGroupOutput struct{ *pulumi.OutputState }

func (PolicyRuleGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PolicyRuleGroup)(nil)).Elem()
}

func (o PolicyRuleGroupOutput) ToPolicyRuleGroupOutput() PolicyRuleGroupOutput {
	return o
}

func (o PolicyRuleGroupOutput) ToPolicyRuleGroupOutputWithContext(ctx context.Context) PolicyRuleGroupOutput {
	return o
}

// The unique identifier of the group.
func (o PolicyRuleGroupOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v PolicyRuleGroup) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the group.
func (o PolicyRuleGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v PolicyRuleGroup) string { return v.Name }).(pulumi.StringOutput)
}

type PolicyRuleGroupArrayOutput struct{ *pulumi.OutputState }

func (PolicyRuleGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PolicyRuleGroup)(nil)).Elem()
}

func (o PolicyRuleGroupArrayOutput) ToPolicyRuleGroupArrayOutput() PolicyRuleGroupArrayOutput {
	return o
}

func (o PolicyRuleGroupArrayOutput) ToPolicyRuleGroupArrayOutputWithContext(ctx context.Context) PolicyRuleGroupArrayOutput {
	return o
}

func (o PolicyRuleGroupArrayOutput) Index(i pulumi.IntInput) PolicyRuleGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PolicyRuleGroup {
		return vs[0].([]PolicyRuleGroup)[vs[1].(int)]
	}).(PolicyRuleGroupOutput)
}

type PolicyRulePortRange struct {
	End   int `pulumi:"end"`
	Start int `pulumi:"start"`
}

// PolicyRulePortRangeInput is an input type that accepts PolicyRulePortRangeArgs and PolicyRulePortRangeOutput values.
// You can construct a concrete instance of `PolicyRulePortRangeInput` via:
//
//	PolicyRulePortRangeArgs{...}
type PolicyRulePortRangeInput interface {
	pulumi.Input

	ToPolicyRulePortRangeOutput() PolicyRulePortRangeOutput
	ToPolicyRulePortRangeOutputWithContext(context.Context) PolicyRulePortRangeOutput
}

type PolicyRulePortRangeArgs struct {
	End   pulumi.IntInput `pulumi:"end"`
	Start pulumi.IntInput `pulumi:"start"`
}

func (PolicyRulePortRangeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PolicyRulePortRange)(nil)).Elem()
}

func (i PolicyRulePortRangeArgs) ToPolicyRulePortRangeOutput() PolicyRulePortRangeOutput {
	return i.ToPolicyRulePortRangeOutputWithContext(context.Background())
}

func (i PolicyRulePortRangeArgs) ToPolicyRulePortRangeOutputWithContext(ctx context.Context) PolicyRulePortRangeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyRulePortRangeOutput)
}

// PolicyRulePortRangeArrayInput is an input type that accepts PolicyRulePortRangeArray and PolicyRulePortRangeArrayOutput values.
// You can construct a concrete instance of `PolicyRulePortRangeArrayInput` via:
//
//	PolicyRulePortRangeArray{ PolicyRulePortRangeArgs{...} }
type PolicyRulePortRangeArrayInput interface {
	pulumi.Input

	ToPolicyRulePortRangeArrayOutput() PolicyRulePortRangeArrayOutput
	ToPolicyRulePortRangeArrayOutputWithContext(context.Context) PolicyRulePortRangeArrayOutput
}

type PolicyRulePortRangeArray []PolicyRulePortRangeInput

func (PolicyRulePortRangeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PolicyRulePortRange)(nil)).Elem()
}

func (i PolicyRulePortRangeArray) ToPolicyRulePortRangeArrayOutput() PolicyRulePortRangeArrayOutput {
	return i.ToPolicyRulePortRangeArrayOutputWithContext(context.Background())
}

func (i PolicyRulePortRangeArray) ToPolicyRulePortRangeArrayOutputWithContext(ctx context.Context) PolicyRulePortRangeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyRulePortRangeArrayOutput)
}

type PolicyRulePortRangeOutput struct{ *pulumi.OutputState }

func (PolicyRulePortRangeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PolicyRulePortRange)(nil)).Elem()
}

func (o PolicyRulePortRangeOutput) ToPolicyRulePortRangeOutput() PolicyRulePortRangeOutput {
	return o
}

func (o PolicyRulePortRangeOutput) ToPolicyRulePortRangeOutputWithContext(ctx context.Context) PolicyRulePortRangeOutput {
	return o
}

func (o PolicyRulePortRangeOutput) End() pulumi.IntOutput {
	return o.ApplyT(func(v PolicyRulePortRange) int { return v.End }).(pulumi.IntOutput)
}

func (o PolicyRulePortRangeOutput) Start() pulumi.IntOutput {
	return o.ApplyT(func(v PolicyRulePortRange) int { return v.Start }).(pulumi.IntOutput)
}

type PolicyRulePortRangeArrayOutput struct{ *pulumi.OutputState }

func (PolicyRulePortRangeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PolicyRulePortRange)(nil)).Elem()
}

func (o PolicyRulePortRangeArrayOutput) ToPolicyRulePortRangeArrayOutput() PolicyRulePortRangeArrayOutput {
	return o
}

func (o PolicyRulePortRangeArrayOutput) ToPolicyRulePortRangeArrayOutputWithContext(ctx context.Context) PolicyRulePortRangeArrayOutput {
	return o
}

func (o PolicyRulePortRangeArrayOutput) Index(i pulumi.IntInput) PolicyRulePortRangeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PolicyRulePortRange {
		return vs[0].([]PolicyRulePortRange)[vs[1].(int)]
	}).(PolicyRulePortRangeOutput)
}

type PolicyRuleState struct {
	// The action to take: 'accept' or 'drop'.
	Action RuleAction `pulumi:"action"`
	// Whether the rule applies bidirectionally.
	Bidirectional bool `pulumi:"bidirectional"`
	// An optional description of the policy rule.
	Description *string `pulumi:"description"`
	// Optional destination resource for the rule.
	DestinationResource *Resource `pulumi:"destinationResource"`
	// Optional list of destination groups.
	Destinations []PolicyRuleGroup `pulumi:"destinations"`
	// Whether the rule is active.
	Enabled bool `pulumi:"enabled"`
	// Optional unique identifier for the policy rule.
	Id *string `pulumi:"id"`
	// The name of the policy rule.
	Name string `pulumi:"name"`
	// Optional list of port ranges.
	PortRanges []PolicyRulePortRange `pulumi:"portRanges"`
	// Optional list of ports.
	Ports []string `pulumi:"ports"`
	// The protocol: 'tcp', 'udp', 'icmp', or 'all'.
	Protocol Protocol `pulumi:"protocol"`
	// Optional source resource for the rule.
	SourceResource *Resource `pulumi:"sourceResource"`
	// Optional list of source groups.
	Sources []PolicyRuleGroup `pulumi:"sources"`
}

type PolicyRuleStateOutput struct{ *pulumi.OutputState }

func (PolicyRuleStateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PolicyRuleState)(nil)).Elem()
}

func (o PolicyRuleStateOutput) ToPolicyRuleStateOutput() PolicyRuleStateOutput {
	return o
}

func (o PolicyRuleStateOutput) ToPolicyRuleStateOutputWithContext(ctx context.Context) PolicyRuleStateOutput {
	return o
}

// The action to take: 'accept' or 'drop'.
func (o PolicyRuleStateOutput) Action() RuleActionOutput {
	return o.ApplyT(func(v PolicyRuleState) RuleAction { return v.Action }).(RuleActionOutput)
}

// Whether the rule applies bidirectionally.
func (o PolicyRuleStateOutput) Bidirectional() pulumi.BoolOutput {
	return o.ApplyT(func(v PolicyRuleState) bool { return v.Bidirectional }).(pulumi.BoolOutput)
}

// An optional description of the policy rule.
func (o PolicyRuleStateOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PolicyRuleState) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Optional destination resource for the rule.
func (o PolicyRuleStateOutput) DestinationResource() ResourcePtrOutput {
	return o.ApplyT(func(v PolicyRuleState) *Resource { return v.DestinationResource }).(ResourcePtrOutput)
}

// Optional list of destination groups.
func (o PolicyRuleStateOutput) Destinations() PolicyRuleGroupArrayOutput {
	return o.ApplyT(func(v PolicyRuleState) []PolicyRuleGroup { return v.Destinations }).(PolicyRuleGroupArrayOutput)
}

// Whether the rule is active.
func (o PolicyRuleStateOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v PolicyRuleState) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Optional unique identifier for the policy rule.
func (o PolicyRuleStateOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PolicyRuleState) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The name of the policy rule.
func (o PolicyRuleStateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v PolicyRuleState) string { return v.Name }).(pulumi.StringOutput)
}

// Optional list of port ranges.
func (o PolicyRuleStateOutput) PortRanges() PolicyRulePortRangeArrayOutput {
	return o.ApplyT(func(v PolicyRuleState) []PolicyRulePortRange { return v.PortRanges }).(PolicyRulePortRangeArrayOutput)
}

// Optional list of ports.
func (o PolicyRuleStateOutput) Ports() pulumi.StringArrayOutput {
	return o.ApplyT(func(v PolicyRuleState) []string { return v.Ports }).(pulumi.StringArrayOutput)
}

// The protocol: 'tcp', 'udp', 'icmp', or 'all'.
func (o PolicyRuleStateOutput) Protocol() ProtocolOutput {
	return o.ApplyT(func(v PolicyRuleState) Protocol { return v.Protocol }).(ProtocolOutput)
}

// Optional source resource for the rule.
func (o PolicyRuleStateOutput) SourceResource() ResourcePtrOutput {
	return o.ApplyT(func(v PolicyRuleState) *Resource { return v.SourceResource }).(ResourcePtrOutput)
}

// Optional list of source groups.
func (o PolicyRuleStateOutput) Sources() PolicyRuleGroupArrayOutput {
	return o.ApplyT(func(v PolicyRuleState) []PolicyRuleGroup { return v.Sources }).(PolicyRuleGroupArrayOutput)
}

type PolicyRuleStateArrayOutput struct{ *pulumi.OutputState }

func (PolicyRuleStateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PolicyRuleState)(nil)).Elem()
}

func (o PolicyRuleStateArrayOutput) ToPolicyRuleStateArrayOutput() PolicyRuleStateArrayOutput {
	return o
}

func (o PolicyRuleStateArrayOutput) ToPolicyRuleStateArrayOutputWithContext(ctx context.Context) PolicyRuleStateArrayOutput {
	return o
}

func (o PolicyRuleStateArrayOutput) Index(i pulumi.IntInput) PolicyRuleStateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PolicyRuleState {
		return vs[0].([]PolicyRuleState)[vs[1].(int)]
	}).(PolicyRuleStateOutput)
}

type Resource struct {
	// The unique identifier of the resource.
	Id string `pulumi:"id"`
	// The type of resource: 'domain', 'host', or 'subnet'.
	Type ResourceType `pulumi:"type"`
}

// ResourceInput is an input type that accepts ResourceArgs and ResourceOutput values.
// You can construct a concrete instance of `ResourceInput` via:
//
//	ResourceArgs{...}
type ResourceInput interface {
	pulumi.Input

	ToResourceOutput() ResourceOutput
	ToResourceOutputWithContext(context.Context) ResourceOutput
}

type ResourceArgs struct {
	// The unique identifier of the resource.
	Id pulumi.StringInput `pulumi:"id"`
	// The type of resource: 'domain', 'host', or 'subnet'.
	Type ResourceTypeInput `pulumi:"type"`
}

func (ResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Resource)(nil)).Elem()
}

func (i ResourceArgs) ToResourceOutput() ResourceOutput {
	return i.ToResourceOutputWithContext(context.Background())
}

func (i ResourceArgs) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceOutput)
}

func (i ResourceArgs) ToResourcePtrOutput() ResourcePtrOutput {
	return i.ToResourcePtrOutputWithContext(context.Background())
}

func (i ResourceArgs) ToResourcePtrOutputWithContext(ctx context.Context) ResourcePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceOutput).ToResourcePtrOutputWithContext(ctx)
}

// ResourcePtrInput is an input type that accepts ResourceArgs, ResourcePtr and ResourcePtrOutput values.
// You can construct a concrete instance of `ResourcePtrInput` via:
//
//	        ResourceArgs{...}
//
//	or:
//
//	        nil
type ResourcePtrInput interface {
	pulumi.Input

	ToResourcePtrOutput() ResourcePtrOutput
	ToResourcePtrOutputWithContext(context.Context) ResourcePtrOutput
}

type resourcePtrType ResourceArgs

func ResourcePtr(v *ResourceArgs) ResourcePtrInput {
	return (*resourcePtrType)(v)
}

func (*resourcePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (i *resourcePtrType) ToResourcePtrOutput() ResourcePtrOutput {
	return i.ToResourcePtrOutputWithContext(context.Background())
}

func (i *resourcePtrType) ToResourcePtrOutputWithContext(ctx context.Context) ResourcePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourcePtrOutput)
}

type ResourceOutput struct{ *pulumi.OutputState }

func (ResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Resource)(nil)).Elem()
}

func (o ResourceOutput) ToResourceOutput() ResourceOutput {
	return o
}

func (o ResourceOutput) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return o
}

func (o ResourceOutput) ToResourcePtrOutput() ResourcePtrOutput {
	return o.ToResourcePtrOutputWithContext(context.Background())
}

func (o ResourceOutput) ToResourcePtrOutputWithContext(ctx context.Context) ResourcePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Resource) *Resource {
		return &v
	}).(ResourcePtrOutput)
}

// The unique identifier of the resource.
func (o ResourceOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v Resource) string { return v.Id }).(pulumi.StringOutput)
}

// The type of resource: 'domain', 'host', or 'subnet'.
func (o ResourceOutput) Type() ResourceTypeOutput {
	return o.ApplyT(func(v Resource) ResourceType { return v.Type }).(ResourceTypeOutput)
}

type ResourcePtrOutput struct{ *pulumi.OutputState }

func (ResourcePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (o ResourcePtrOutput) ToResourcePtrOutput() ResourcePtrOutput {
	return o
}

func (o ResourcePtrOutput) ToResourcePtrOutputWithContext(ctx context.Context) ResourcePtrOutput {
	return o
}

func (o ResourcePtrOutput) Elem() ResourceOutput {
	return o.ApplyT(func(v *Resource) Resource {
		if v != nil {
			return *v
		}
		var ret Resource
		return ret
	}).(ResourceOutput)
}

// The unique identifier of the resource.
func (o ResourcePtrOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Resource) *string {
		if v == nil {
			return nil
		}
		return &v.Id
	}).(pulumi.StringPtrOutput)
}

// The type of resource: 'domain', 'host', or 'subnet'.
func (o ResourcePtrOutput) Type() ResourceTypePtrOutput {
	return o.ApplyT(func(v *Resource) *ResourceType {
		if v == nil {
			return nil
		}
		return &v.Type
	}).(ResourceTypePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyRuleArgsInput)(nil)).Elem(), PolicyRuleArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyRuleArgsArrayInput)(nil)).Elem(), PolicyRuleArgsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyRulePortRangeInput)(nil)).Elem(), PolicyRulePortRangeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyRulePortRangeArrayInput)(nil)).Elem(), PolicyRulePortRangeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceInput)(nil)).Elem(), ResourceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourcePtrInput)(nil)).Elem(), ResourceArgs{})
	pulumi.RegisterOutputType(PolicyRuleArgsOutput{})
	pulumi.RegisterOutputType(PolicyRuleArgsArrayOutput{})
	pulumi.RegisterOutputType(PolicyRuleGroupOutput{})
	pulumi.RegisterOutputType(PolicyRuleGroupArrayOutput{})
	pulumi.RegisterOutputType(PolicyRulePortRangeOutput{})
	pulumi.RegisterOutputType(PolicyRulePortRangeArrayOutput{})
	pulumi.RegisterOutputType(PolicyRuleStateOutput{})
	pulumi.RegisterOutputType(PolicyRuleStateArrayOutput{})
	pulumi.RegisterOutputType(ResourceOutput{})
	pulumi.RegisterOutputType(ResourcePtrOutput{})
}
