name: netbird
description: A Pulumi provider for NetBird.
runtime: go

language:
  go:
    moduleName: github.com/mbrav/pulumi-netbird/sdk/go/netbird

resources:
  netbird:index:Random:
    isComponent: false
    inputProperties:
      length:
        type: integer
        description: Number of characters in the password
    required:
      - length
    properties:
      result:
        type: string
        description: The generated password

  netbird:index:RandomComponent:
    isComponent: true
    inputProperties:
      name:
        type: string
    required:
      - name
    properties:
      password:
        type: string
