name: Run Acceptance Tests on main

permissions: read-all

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/stage-lint.yaml
  build:
    uses: ./.github/workflows/stage-build.yaml
