name: Lint

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    container: golangci/golangci-lint:v2.12.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ✅
        uses: actions/checkout@v6

      - name: Lint 🧹
        run: make lint
